(function(root,factory){const api=factory();if(typeof module==='object')module.exports=api;else root.PABoxCopy=api;})(typeof globalThis!=='undefined'?globalThis:this,()=>{
 'use strict';
 // Short material titles describe the problem topic; worked examples explain the operation.
 // Display illustrations only: never add their numbers or formulas to a plan/request.
 const entry=(name,example,description)=>({name,example,description});
 const atoms={
  'PA-MOTIF-S01-01':entry('정적분으로 정의된 함수',String.raw`$G(x)=\int_0^x(x^2-t^2)\,dt$이면 $G'(x)=2x\cdot x$. 적분을 먼저 계산하지 않아도 돼요.`),
  'PA-MOTIF-S01-02':entry('정적분의 부호',String.raw`$\int_2^x(t^2+1)\,dt$는 $x>2$에서 양수, $x<2$에서 음수예요.`),
  'PA-MOTIF-S01-03':entry('극값의 개수',String.raw`$G'(x)=(x-1)(x-3)(x-a)$일 때 $a=1$이면, $x=3$에서만 부호가 바뀌어 극값이 하나예요.`),
  'PA-MOTIF-S01-04':entry('함수의 연속 조건',String.raw`$g(x)=\frac{|x|}{x}|f(x)|$를 $x=0$에서도 연속으로 이으려면 $f(0)=g(0)=0$이어야 해요.`),
  'PA-MOTIF-S01-05':entry('절댓값 함수의 미분가능성',String.raw`$|x-1|$은 $x=1$에서 꺾이지만, $|(x-1)^2|$은 매끈하게 이어져요.`),
  'PA-MOTIF-S01-06':entry('그래프의 평행이동',String.raw`$F$가 $x=2$에서 극값을 가지면, $H(x)=F(x+2)-F(2)$는 그 점이 $(0,0)$으로 옮겨져요.`),
  'PA-MOTIF-S01-07':entry('정적분과 함숫값의 차',String.raw`$F(x)=x^2+C$이면 $F(x)-F(1)=x^2-1$. $C$를 몰라도 식을 구해요.`),
  'PA-MOTIF-S01-08':entry('구간별 함수의 미분가능성',String.raw`$x<1$에서는 $x^2$, $x\ge1$에서는 $ax+b$라면, $x=1$에서 미분가능할 조건은 $a=2$, $b=-1$이에요.`),
  'PA-MOTIF-S01-09':entry('ㄱ·ㄴ·ㄷ 참거짓',String.raw`ㄱ에서만 $a=0$을 가정했다면, ㄴ을 판단할 때는 $a=0$을 그대로 쓰지 않아요.`),
  'PA-MOTIF-S01-10':entry('합성함수 방정식',String.raw`$F$의 근이 $0,2$뿐이면, $F(x-F(x))=0$은 $F(x)=x$ 또는 $F(x)=x-2$로 나눠요.`),
  'PA-MOTIF-S01-11':entry('직선과 곡선의 교점',String.raw`$F(x)=\frac14x(x-2)^2$이면 $F(x)-x=\frac14x^2(x-4)$. 직선 $y=x$는 $x=0$에서 접하고 $x=4$에서도 만나요.`),
  'PA-MOTIF-S01-12':entry('접선의 기울기',String.raw`$F(x)=x^3-3x$의 기울기가 $0$인 점은 $x=-1,1$ 두 곳이에요. 함숫값 조건까지 보고 골라요.`),
  'PA-MOTIF-S01-13':entry('함숫값 조건으로 함수 선택',String.raw`후보가 $F(x)=x^2$, $F(x)=2x^2$이고 $F(1)=2$라면 두 번째만 남아요.`),
  'PA-S02-LEVELS-01':entry('절댓값이 포함된 식',String.raw`$x^2+1$은 항상 양수라서, $|(x-1)(x^2+1)|$은 $x=1$을 기준으로 식을 나눠요.`),
  'PA-S02-LEVELS-02':entry('개수함수',String.raw`$y=x^2$와 $y=a$가 두 점에서 만나려면 $a>0$이어야 해요.`),
  'PA-S02-LEVELS-03':entry('정수의 개수와 합',String.raw`$1<a\le4$이면 정수 $a$는 $2,3,4$. 개수는 $3$, 합은 $9$예요.`),
  'PA-S02-JUMP-01':entry('좌미분계수와 우미분계수의 합',String.raw`$y=|x|$의 $x=0$에서 왼쪽 기울기는 $-1$, 오른쪽 기울기는 $1$. 두 기울기의 합은 $0$이에요.`, '좌우 차를 나눈 극한을 양쪽 미분계수의 합으로 읽어요. 두 기울기가 같다는 뜻은 아니에요.'),
  'PA-S02-JUMP-02':entry('함수의 곱과 연속',String.raw`$x=0$에서 $g(x)$의 왼쪽 극한은 $1$, 오른쪽 극한은 $-1$이라면, 다항식 $f$와의 곱이 연속이려면 $f(0)=0$이 필요해요.`, '서로 다른 유한한 좌우 극한을 다른 인수의 0으로 연결해요. 그 점에 정의한 값도 확인해요.'),
  'PA-S02-JUMP-03':entry('가장 작은 실근',String.raw`한 번만 나타나는 근 $1$ 때문에 $2$만큼 왼쪽인 $-1$도 근이어야 한다면, $1$은 가장 작은 근이 될 수 없어요.`),
  'PA-S02-JUMP-04':entry('서로 다른 실근의 개수',String.raw`한 식의 해가 $1,2$, 다른 식의 해가 $2,3$이면 서로 다른 해는 $1,2,3$ 세 개예요.`),
  'PA-S02-RECURRENCE-01':entry('구간별 함수의 연결 조건',String.raw`$[0,1]$에서 $f(x)=x^2$, $f(x+1)=f(x)+ax+b$라면, $x=1$에서 값과 기울기를 맞춰 $a=2$, $b=1$을 얻어요.`),
  'PA-S02-RECURRENCE-02':entry('정적분의 구간 이동',String.raw`$f(x+1)=f(x)+2x+1$이면 $\int_1^2 f(x)\,dx$를 $\int_0^1\{f(t)+2t+1\}\,dt$로 바꿔요.`),
  'PA-S02-RECURRENCE-03':entry('함수의 관계식과 구간별 식',String.raw`$[0,1]$에서 $f(x)=x^2$이고 $f(x+1)=f(x)+2x+1$이면, $[1,2]$에서도 $f(x)=x^2$예요.`),
  'PA-S02-WINDOW-01':entry('움직이는 구간 속 두 점',String.raw`$1,3$이 모두 $[a,a+3]$ 안에 있으려면 $0\le a\le1$이어야 해요.`),
  'PA-S02-WINDOW-02':entry('두 근 사이의 간격',String.raw`길이 $3$인 닫힌구간에 두 근이 함께 들어가는 위치가 딱 한 곳이면, 두 근의 간격은 $3$이에요.`),
  'PA-S02-WINDOW-03':entry('지나는 점들로 함수 작성',String.raw`삼차함수에서 $F(1)=F(3)=2$이면 $F(x)-2=k(x-1)(x-3)(x-r)$로 쓸 수 있어요.`),
  'PA-S02-WINDOW-04':entry('추가 조건으로 함수 선택',String.raw`후보가 $F(x)=x(x-1)$, $F(x)=x(x-2)$이고 $F(2)=0$이면 두 번째가 남아요.`),
  'PA-S02-SIGNED-01':entry('정적분과 적분상수',String.raw`$F(x)=\int_2^x f(t)\,dt$라면 $x=2$를 넣어 바로 $F(2)=0$을 얻어요.`),
  'PA-S02-SIGNED-02':entry('미분가능 조건과 중근',String.raw`연결 조건으로 다항식 $F$의 $F(1)=F'(1)=0$을 얻었다면, $F(x)$에 $(x-1)^2$이 인수로 들어가요.`),
  'PA-S02-SIGNED-03':entry('구간별 방정식의 해',String.raw`$x<0$에서 쓰는 식을 풀어 $x=-1,2$가 나왔다면 $-1$만 남겨요.`),
  'PA-S02-TRAVEL-01':entry('위치와 이동거리',String.raw`위치 $0$에서 $3$까지 갔다가 $1$로 돌아오면, 위치 차이는 $1$이지만 이동거리는 $3+2=5$예요.`),
  'PA-S02-TRAVEL-02':entry('방향 전환과 이동거리',String.raw`위치가 $0\to3\to1$로 변하고 각 구간에서 방향이 일정하면, 이동거리는 $|3-0|+|1-3|=5$예요.`),
  'PA-S02-TRAVEL-03':entry('정지 시각과 위치함수',String.raw`위치가 $X(t)=t^2+at$이고 $t=2$에서 멈추면, $X'(2)=4+a=0$에서 $a=-4$예요.`),
  'PA-S02-TRAVEL-04':entry('왕복 거리와 최대 거리',String.raw`출발점으로 돌아왔고 총 $10$만큼 움직였다면, 출발점에서 떨어진 거리는 $5$를 넘을 수 없어요.`),
  'PA-OP-FIXED-LEVELS':entry('수평선과 그래프의 교점',String.raw`$y=x^2$와 $y=0$은 한 점, $y=1$은 두 점에서 만나요.`),
  'PA-CAND-SKL-20260910-033':entry('절댓값이 있는 분수',String.raw`$u=2$이면 $|u|/u=1$, $u=-2$이면 $-1$이에요. $u=0$에서는 나눌 수 없어요.`),
  'PA-CAND-SKL-20260914-001':entry('절댓값의 합과 차',String.raw`$|x|+x$는 $x\ge0$에서 $2x$, $x<0$에서 $0$이에요. $|x|-x$는 각각 $0$, $-2x$예요.`),
  'PA-BRIDGE-01':entry('함수의 차와 교점',String.raw`$F(x)=x-2$를 풀 때 $H(x)=F(x)-x$로 두면, $H(x)=-2$인 점을 찾는 문제로 바뀌어요.`),
  'PA-BRIDGE-02':entry('함수의 증가·감소와 극값',String.raw`$F(x)=x^3-3x$이면 $F'(x)=3(x-1)(x+1)$. $-1,1$을 기준으로 증가·감소가 바뀌어요.`),
  'PA-BRIDGE-03':entry('후보 중 정수',String.raw`가능한 $a$가 $1,\sqrt2$뿐이면 이 두 값만 넘겨요. 그중 정수는 $1$이에요.`, '앞에서 얻은 후보 목록을 그대로 이어 써요. 두 값 사이의 수를 새 후보로 추가하지 않아요.'),
  'PA-BRIDGE-04':entry('도함수로 원래 함수 작성',String.raw`$F'(x)=2x$, $F(0)=3$이면 $F(x)=x^2+3$이에요.`),
  'PA-BRIDGE-05':entry('교점 개수와 상수의 범위',String.raw`수평선이 $y=a$이고 허용 높이가 $1<y\le4$라면, 그대로 $1<a\le4$예요.`),
  'PA-BRIDGE-06':entry('다항식의 근과 중근',String.raw`$F(x)=(x-1)^2(x+2)$이면 근은 $1,-2$. $(x-1)$은 두 번, $(x+2)$는 한 번 곱해졌어요.`),
  'PA-BRIDGE-07':entry('함수 그래프와 위치',String.raw`$X(t)=(t-1)^2$, $0\le t\le2$를 위치로 읽으면, $t=1$에서 움직이는 방향이 바뀌어요.`),
  'PA-BRIDGE-08':entry('같은 함숫값과 삼차함수의 극값',String.raw`$F(x)=x^3-3x$는 $F(0)=F(\sqrt3)=0$이고, $x=-1,1$ 두 곳에서 극값을 가져요.`),
  'PA-BRIDGE-09':entry('정수의 합으로 함수 찾기',String.raw`정수인 후보의 합이 $4$이면, 정수가 하나일 때는 그 값이 $4$, 두 개일 때는 두 값의 합이 $4$예요. 각 경우를 함수에 다시 대입해요.`)
 };
 const starts={
  'PA-MOTIF-S01-10':entry('합성함수 방정식',String.raw`$F(x-F(x))=0$을 직선과 곡선이 만나는 문제로 바꿔요.`),
  'PA-MOTIF-S01-03':entry('극값의 개수',String.raw`$G'(x)=(x-1)(x-3)(x-a)$에서 $a$를 정해 극값을 하나만 남겨요.`),
  'PA-BRIDGE-04':entry('도함수로 원래 함수 작성',String.raw`$F'(x)=2x$, $F(0)=3$에서 $F(x)=x^2+3$을 찾아요.`)
 };
 const goals={
  integer_answer:entry('가능한 정수는 몇 개? 합은 얼마?',String.raw`가능한 $a$가 $1,\sqrt2$일 때, 정수 $a$의 합을 구하여라.`),
  finite_parameter_set:entry('조건에 맞는 a의 값은?',String.raw`극값이 하나만 생기게 하는 모든 $a$의 값을 구하여라.`),
  level_counts:entry('만나는 점이나 서로 다른 해는 몇 개?',String.raw`$y=x^2$와 $y=1$의 교점은 몇 개인가?`),
  height_set:entry('높이를 어디까지 움직일 수 있을까?',String.raw`$y=x^2$와 $y=a$가 두 점에서 만나도록 하는 $a$의 범위를 구하여라.`),
  distance_result:entry('실제로 움직인 거리는 얼마?',String.raw`위치가 $0\to3\to1$로 움직였다. 방향이 바뀐 곳에서 나눠 총 이동거리를 구하여라.`),
  distance_bound:entry('출발점에서 얼마나 멀리 갈 수 있을까?',String.raw`총 $10$만큼 움직여 출발점으로 돌아왔다. 출발점에서 떨어질 수 있는 최대 거리는?`),
  tested_candidates:entry('후보 중 모든 조건에 맞는 함수는?',String.raw`$F(x)=x^2$ 또는 $2x^2$ 중 $F(1)=2$인 함수를 골라라.`),
  candidate_functions:entry('가능한 함수식은 무엇일까?',String.raw`$F'(x)=2x$이고 $F(0)=1$ 또는 $2$일 때, 가능한 $F(x)$를 모두 구하여라.`),
  distinct_roots:entry('겹치는 해를 빼면 몇 개일까?',String.raw`한 식의 해는 $1,2$, 다른 식의 해는 $2,3$이다. 서로 다른 해는 몇 개인가?`),
  shifted_integral:entry('구간을 옮겨 적분값 구하기',String.raw`$[0,1]$에서 아는 식을 이용해 $\int_1^2 f(x)\,dx$를 구하여라.`),
  next_interval:entry('다음 구간에서는 어떤 식일까?',String.raw`$[0,1]$의 식과 $f(x+1)=f(x)+2x+1$로 $[1,2]$에서의 식을 구하여라.`),
  boundary_equations:entry('두 식을 매끄럽게 잇는 계수는?',String.raw`$x^2$와 $ax+b$를 $x=1$에서 미분가능하게 잇는 $a,b$를 구하여라.`),
  factor_zero:entry('곱이 끊기지 않으려면 어떤 값이어야 할까?',String.raw`$g$가 $0$에서 서로 다른 유한한 좌우 극한을 가질 때, $f(x)g(x)$가 연속이려면 다항식 $f$의 $f(0)$은?`),
  signed_corners:entry('그래프가 꺾여 미분할 수 없는 곳은?',String.raw`$y=|(x-1)(x+2)|$에서 미분할 수 없는 $x$를 모두 구하여라.`),
  root_gap:entry('두 근은 얼마나 떨어져 있을까?',String.raw`길이 $3$인 구간에 두 근이 함께 들어가는 위치가 딱 한 곳이다. 두 근의 간격은?`),
  position_coefficients:entry('움직임 조건에 맞는 위치식의 계수는?',String.raw`$X(t)=t^2+at$인 물체가 $t=2$에서 멈춘다. $a$를 구하여라.`),
  root_shape_candidates:entry('근은 어디에, 몇 번씩 나타날까?',String.raw`$(x-1)^2(x+2)$에서 근의 위치와 각 인수가 곱해진 횟수를 찾아라.`),
  claim_results:entry('ㄱ·ㄴ·ㄷ 중 옳은 것은?',String.raw`ㄱ은 연속 조건, ㄴ은 미분가능 조건으로 각각 판단하여 옳은 보기를 골라라.`),
  repeated_factor:entry('어떤 인수가 두 번 이상 들어갈까?',String.raw`다항식 $F$에서 $F(1)=F'(1)=0$이다. 반복되는 인수를 찾아라.`)
 };
 const facts={
  difference_integral:String.raw`$\int_0^x\{F(x)-F(t)\}\,dt$`,
  continuous_weight:String.raw`적분 안에서 곱하는 함수가 $w(t)=t^2+1$.`,
  derivative_product:String.raw`$G'(x)=F'(x)\int_1^x(t^2+1)\,dt$`,
  positive_intervals:String.raw`$u<v$이면 $\int_u^v t^2\,dt>0$. 한 점에서만 $0$이어도 적분값은 양수.`,
  zero_weight_interval:String.raw`$0\le t\le1$에서 $w(t)=0$.`,
  changing_weight_sign:String.raw`$w(t)=t$는 $0$을 기준으로 음수에서 양수로 바뀜.`,
  integral_sign:String.raw`$\int_1^x(t^2+1)\,dt$의 부호는 $x-1$의 부호와 같음.`,
  two_simple_critical_roots:String.raw`$F'(x)=3(x-1)(x-3)$`,
  one_extremum_required:String.raw`극대 또는 극소가 생기는 $x$가 딱 하나.`,
  finite_parameter_set:String.raw`가능한 값이 $a=1,\sqrt2$ 두 개뿐.`,
  admissible_set:String.raw`$1<a\le4$ 또는 $a\in\{1,3\}$.`,
  integer_answer:String.raw`$1<a\le4$인 정수는 $2,3,4$이므로 개수 $3$, 합 $9$.`,
  signed_absolute:String.raw`$x\ne0$에서 $g(x)=\frac{|x|}{x}|F(x)|$.`,
  polynomial:String.raw`$F(x)=ax^3+bx+c$`,
  continuous_required:String.raw`$x=1$에서 왼쪽 극한, 오른쪽 극한, 함숫값이 모두 같아야 함.`,
  origin_zero:String.raw`두 식을 잇는 곳이 $x=0$이고 $F(0)=0$.`,
  point_value_defined:String.raw`$x\ne0$의 식과 별도로 $g(0)=0$을 정함.`,
  polynomial_known:String.raw`$F(x)=x^3-3x$처럼 식의 계수가 모두 정해져 있음.`,
  root_multiplicities:String.raw`$(x-1)^2(x+2)$에서 근 $1$은 두 번, $-2$는 한 번 나타남.`,
  signed_corners:String.raw`$\frac{|x|}{x}|x(x-1)|$은 $x=1$에서 꺾임. $x=0$의 값은 $0$으로 따로 정함.`,
  critical_points:String.raw`$F'(x)=0$인 곳이 $x=-1,1$.`,
  shift_constraints:String.raw`극값이 생기는 점을 왼쪽으로만 옮겨 원점에 놓아야 함.`,
  candidate_functions:String.raw`$F(x)=x^2$ 또는 $F(x)=2x^2$.`,
  selection_condition:String.raw`후보 함수가 $F(1)=2$를 만족해야 함.`,
  tested_candidates:String.raw`두 후보에 $F(1)=2$를 넣어 $F(x)=2x^2$만 남음.`,
  derivative_known:String.raw`$F'(x)=3x^2-3$`,
  anchor_value:String.raw`$F(0)=3$`,
  normalized_pieces:String.raw`왼쪽은 $F(x)-F(1)$, 오른쪽은 $F(x)-F(2)$.`,
  value_match:String.raw`$x=1$에서 두 식의 값이 모두 $2$.`,
  slope_match:String.raw`$x=1$에서 왼쪽·오른쪽 기울기가 모두 $3$.`,
  differentiability_required:String.raw`$x=1$에서 함수가 이어지고 좌우 미분계수가 같아야 함.`,
  boundary_equations:String.raw`$x^2$와 $ax+b$를 $x=1$에서 매끄럽게 잇기 위한 $a+b=1$, $a=2$.`,
  separate_claims:String.raw`ㄱ에서만 $a=0$, ㄴ에서는 별도로 $a>0$을 가정.`,
  claim_results:String.raw`ㄱ은 참, ㄴ은 거짓, ㄷ은 참으로 각각 판정.`,
  composite_equation:String.raw`$F(x-F(x))=0$`,
  two_distinct_roots:String.raw`$F(u)=0$의 서로 다른 해가 $u=0,2$뿐.`,
  nonzero_scale:String.raw`$m=2$이면 직선의 기울기 $1/m$을 쓸 수 있음.`,
  parallel_intersections:String.raw`$y=F(x)$와 $y=x$, $y=x-2$의 교점 찾기.`,
  original_composite_family:String.raw`원문처럼 $m=1$로 두고, 삼차식의 근과 계수 조건을 함께 유지.`,
  tangent_candidates:String.raw`$F(x)-x$에 $(x-1)^2$이 인수로 들어가는 함수 후보.`,
  slope_point_condition:String.raw`$F'(2)=1$`,
  known_value_condition:String.raw`$F(2)=3$`,
  root_lists:String.raw`첫 식의 해는 $1,2$, 두 번째 식의 해는 $2,3$.`,
  distinct_roots:String.raw`$1,2,2,3$에서 같은 값 $2$를 한 번만 세어 $1,2,3$.`,
  positive_quadratic_factor:String.raw`$|(x-1)(x^2+1)|$에서 $x^2+1$은 항상 양수.`,
  piecewise_formula:String.raw`$|x|$를 $x<0$에서 $-x$, $x\ge0$에서 $x$로 나눔.`,
  graph_profile:String.raw`$x^3-3x$는 $x=-1$에서 극대 $2$, $x=1$에서 극소 $-2$.`,
  horizontal_problem:String.raw`곡선 $y=x^2$와 수평선 $y=a$의 교점 찾기.`,
  requested_count:String.raw`서로 다른 교점이 정확히 $2$개여야 함.`,
  height_set:String.raw`교점이 두 개가 되는 높이가 $a>0$.`,
  symmetric_difference:String.raw`$\lim_{h\to0}\frac{|F(a+h)|-|F(a-h)|}{h}$`,
  one_sided_derivatives:String.raw`$|x|$의 $0$에서의 좌미분계수는 $-1$, 우미분계수는 $1$.`,
  finite_jump:String.raw`$x=0$에서 왼쪽 극한은 $1$, 오른쪽 극한은 $-1$.`,
  continuous_factor:String.raw`끊기는 함수 $g(x)$에 다항식 $f(x)=x$를 곱함.`,
  product_continuity:String.raw`$g$는 끊겨도 곱 $f(x)g(x)$는 $x=0$에서 이어져야 함.`,
  factor_zero:String.raw`다른 인수의 끊김을 연결하기 위해 $f(0)=0$.`,
  positive_shift_root_rule:String.raw`한 번만 나타나는 근 $r$이 있으면 $r-2$도 근이어야 함.`,
  finite_polynomial_roots:String.raw`$F(x)=(x-1)^2(x+2)$의 근은 $1,-2$뿐.`,
  root_shape_candidates:String.raw`한 근이 두 번 나타나는 $(x-a)^2(x-b)$ 형태.`,
  known_interval:String.raw`$0\le x\le1$에서 $f(x)=x^2$.`,
  recurrence_relation:String.raw`$f(x+1)=f(x)+ax+b$`,
  recurrence_constants:String.raw`$a=2$, $b=1$로 정해져 $f(x+1)=f(x)+2x+1$.`,
  shifted_integral:String.raw`$\int_1^2 f(x)\,dx$를 $\int_0^1 f(t+1)\,dt$로 바꿈.`,
  next_interval:String.raw`$[0,1]$의 식을 이용해 $[1,2]$에서 $f(x)=x^2$임을 알아냄.`,
  two_points:String.raw`수직선 위의 두 점 $1,3$.`,
  closed_window:String.raw`길이 $3$이고 양끝을 포함하는 $[a,a+3]$.`,
  window_positions:String.raw`$1,3$이 모두 $[a,a+3]$에 들어가는 $0\le a\le1$.`,
  window_limit_bound:String.raw`개수를 세는 함수 $N$에 대해 모든 $a$에서 $\lim_{x\to a-}N(x)+\lim_{x\to a+}N(x)\le2$.`,
  window_two_exists:String.raw`어떤 $a$에서는 $[a,a+3]$에 두 점이 모두 들어감.`,
  root_gap:String.raw`두 근이 $1,4$이면 간격은 $3$.`,
  equal_values:String.raw`$F(1)=F(3)=2$`,
  cubic_leading:String.raw`$F(x)=2x^3+ax^2+bx+c$에서 최고차항 계수는 $2$.`,
  factored_family:String.raw`$F(x)-2=k(x-1)(x-3)(x-r)$`,
  definite_integral_definition:String.raw`$F(x)=\int_2^x f(t)\,dt$`,
  base_zero:String.raw`$\int_2^2 f(t)\,dt=0$`,
  opposite_integral_pieces:String.raw`$x<0$에서는 $-\int_0^x f(t)\,dt$, $x\ge0$에서는 $\int_0^x f(t)\,dt$.`,
  continuity_at_boundary:String.raw`$x=0$의 왼쪽·오른쪽 극한이 정의한 값 $F(0)$과 같음.`,
  repeated_factor:String.raw`$(x-1)^2$이 인수로 들어가므로 $F(1)=F'(1)=0$.`,
  piece_roots:String.raw`왼쪽 구간의 식을 풀면 $-1,2$, 오른쪽 식을 풀면 $0,3$.`,
  piece_domains:String.raw`첫 식은 $x<0$에서만, 두 번째 식은 $x\ge0$에서만 사용.`,
  position_velocity:String.raw`위치 $X(t)=t^2$이면 속도 $v(t)=2t$.`,
  time_interval:String.raw`$0\le t\le3$ 동안의 움직임만 살핌.`,
  distance_definition:String.raw`$0$부터 $3$까지의 이동거리는 $\int_0^3|v(t)|\,dt$.`,
  turn_times:String.raw`$v(t)=t-1$이면 $t=1$을 지나며 방향이 바뀜.`,
  position_values:String.raw`출발 위치 $0$, 방향 전환 위치 $3$, 도착 위치 $1$.`,
  distance_result:String.raw`$0\to3\to1$로 움직이면 이동거리 $5$, 출발점에서 가장 멀어진 거리 $3$.`,
  position_family:String.raw`$X(t)=t^3+at^2+bt$`,
  zero_velocity_time:String.raw`$t=2$에서 $v(2)=0$.`,
  position_coefficients:String.raw`$X(t)=t^2+at$가 $t=2$에서 멈추므로 $a=-4$.`,
  same_end_position:String.raw`$X(0)=X(4)$로 출발 위치와 도착 위치가 같음.`,
  total_distance:String.raw`주어진 시간 동안 움직인 거리의 합이 $10$.`,
  distance_bound:String.raw`왕복하여 출발점으로 돌아왔고 총 이동거리가 $10$이면, 출발점과의 거리는 $5$ 이하.`,
  ratio_absolute:String.raw`$\frac{|x-1|}{x-1}$`,
  nonzero_domain:String.raw`분모가 $x-1$이면 $x\ne1$.`,
  sign_expression:String.raw`$x>0$에서 $1$, $x<0$에서 $-1$인 식.`,
  absolute_sum:String.raw`$|x|+x$ 또는 $|x|-x$.`,
  real_domain:String.raw`$|x|+x$는 $x=0$을 포함한 모든 실수에서 정의됨.`,
  linear_shear_relation:String.raw`$H(x)=F(x)-x$로 두면 $F(x)=x+2$는 $H(x)=2$.`,
  turn_profile:String.raw`위치가 처음에는 감소하다 $t=1$ 이후 증가함.`,
  origin_returns:String.raw`$X(0)=0$인 물체가 $t=4$에서 다시 $X(4)=0$.`,
  all_roots_with_multiplicity:String.raw`$(x-1)^2(x+2)$의 근을 반복까지 써서 $1,1,-2$.`,
  root_sum:String.raw`반복까지 센 근이 $1,1,-2$이면 합은 $0$.`,
  common_value:String.raw`$F(1)=F(3)=2$에서 공통 함숫값은 $2$.`,
  division_by_zero:String.raw`$|x|/x$에 $x=0$을 그대로 대입하려는 경우.`,
  constant_cancelled:String.raw`$F(x)=x^2+C$에서 $F(x)-F(0)=x^2$가 되어 $C$가 사라짐.`,
  constant_target:String.raw`$F(x)-F(0)=x^2$만 알면서 $F(0)$을 구하라고 요구함.`,
  jump_unbounded:String.raw`$1/x$가 $x\to0+$에서 끝없이 커짐.`,
  zero_location_only:String.raw`근이 $1$인 것만 알고, $(x-1)$인지 $(x-1)^2$인지는 모름.`,
  degree_at_least_two:String.raw`이차식 $x^2+1$ 또는 삼차식 $x^3-3x$.`,
  nonconstant_polynomial:String.raw`$x^2+1$처럼 $x$에 따라 값이 달라지는 다항식.`,
  nonzero_polynomial:String.raw`$x^2$은 $x=0$에서만 $0$이므로 모든 곳에서 $0$인 식은 아님.`,
  nonzero_derivative:String.raw`$F'(x)=2x$는 항상 $0$인 도함수가 아님.`,
  differentiable_function:String.raw`$F(x)=x^3$처럼 다루는 구간의 모든 점에서 미분가능.`,
  recurrence_unique_constants:String.raw`끝점 조건이 $a+b=3$, $a=2$가 되어 $a,b$가 하나로 정해짐.`,
  height_identity:String.raw`수평선을 $y=a$로 놓아 높이 자체가 $a$. $y=a^2$와는 다름.`,
  zero_scale:String.raw`$m=0$이면 $F(x-mF(x))=F(x)$가 되어 별도 처리.`,
  fixed_heights:String.raw`교점을 셀 수평선이 $y=0$, $y=2$로 정해져 있음.`,
  level_counts:String.raw`$y=x^2$는 높이 $0$에서 한 점, 높이 $2$에서 두 점을 만남.`,
  parameter_is_critical_root:String.raw`허용되는 $a$가 정확히 $F'(x)=0$의 두 해.`,
  cubic_one_free_root:String.raw`$F(x)=(x-1)(x-3)(x-r)$에서 $r$만 아직 모름.`,
  nonzero_integer_root_sum:String.raw`가능한 $a$ 중 정수인 값만 더한 결과가 $4$.`,
  zero_integer_root_sum:String.raw`정수 후보가 $-1,1$이면 합은 $0$. 정수 후보가 없어도 합은 $0$.`
 };
 return {atoms,starts,goals,facts};
});
