(async()=>{'use strict';
const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;};
const btn=(text,fn,cls)=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;};
const clone=x=>structuredClone(x),factKey=f=>JSON.stringify([f.type,f.subject,f.object||null,f.scope]);
function save(value,name,type='application/json'){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function math(text,tag='p'){const p=el(tag),pattern=/\$\$([\s\S]+?)\$\$|\$([^$\n]+?)\$/g;let at=0;for(const m of text.matchAll(pattern)){p.append(document.createTextNode(text.slice(at,m.index)));const span=el('span');katex.render(m[1]||m[2],span,{displayMode:Boolean(m[1]),throwOnError:false,trust:false,maxExpand:1000});p.append(span);at=m.index+m[0].length;}p.append(document.createTextNode(text.slice(at)));return p;}
try{
 const response=await fetch('connection-registry.json',{cache:'no-store'});if(!response.ok)throw Error('자산을 읽지 못했습니다.');
 const registry=await response.json(),engine=PAConnections.create(registry),ops=new Map(registry.operations.map(o=>[o.id,o])),session=PASession.create(),S=PASelection,P=PAPlanner,C=PABoxCopy,G=PAGraph,U=PACurriculum;let productionIO=null;
 const reviewStore=PAReviewClient.create(session);let reviewLoadError='';
 async function refreshReviews(){try{await reviewStore.load();reviewStore.attach(registry);reviewLoadError='';return true;}catch(e){reviewLoadError=e.message;return false;}}
 await refreshReviews();
 const nameOf=id=>PABoxExamples.get(id)?.name||C.atoms[id]?.name||ops.get(id)?.name||id;
 const goalName=type=>C.goals[type]?.name||P.GOALS[type]||registry.types[type];
 function example(text,compact=false){if(!text)return document.createDocumentFragment();const box=el('span',null,'box-example'+(compact?' compact':''));box.append(el('span','예시','example-label'));const body=math(text,'span');body.className='example-body';box.append(body);return box;}
 let coreId=null,target=null,undoSelection=null,unitScope=null;
 let mapState={roles:{},positions:{}};
 let plan=S.blank(registry),disabled=new Set(),category='all',source='',onlySelected=false,calculation=0,reasoning=1,pending=null,activeJob=null,pollTimer=null,busy=false,sessionReady=false;
 const origins=op=>[...new Set(registry.records.filter(r=>op.supports.includes(r.id)).map(r=>r.origin))];
 const originName=o=>o==='seminar-01'?'1차 세미나':o==='seminar-02'?'2차 세미나':o==='shared'?'공유 자산':o;
 const calcChoices=[['가볍게','전개와 큰 수 계산 줄이기'],['적당히','핵심 식을 세운 뒤 계산'],['충분히','여러 단계 계산 허용']];
 const reasonChoices=[['단순','배운 방법을 바로 찾아 적용'],['심화','조건들을 연결해 풀이 방향 찾기'],['킬러','숨은 관계 발견과 경우 검토 요구']];
 const effective=()=>({...clone(plan),facts:plan.facts.filter(f=>!disabled.has(factKey(f))).map(clone)});
 function message(t){$('selectionMessage').textContent=t;$('selectionNotice').textContent=t;}
 const selectionState=()=>({plan:clone(plan),disabled:[...disabled],coreId,target:clone(target),mapState:clone(mapState),unitScope:clone(unitScope)});
 const signature=()=>JSON.stringify(selectionState());
 function replaceSelection(next,text){const before=selectionState(),previous=undoSelection?.after===signature()?undoSelection:null;unitScope=U.normalize(next.unitScope===undefined?unitScope:next.unitScope);plan=clone(next.plan);disabled=new Set(next.disabled||[]);coreId=S.validCore(plan,next.coreId)||plan.nodes.at(-1)?.id||null;target=coreId?(next.target||null):null;mapState=G.state(next.mapState,plan);plan.nodes=G.compile(effective(),registry).plan.nodes;undoSelection={before,after:signature(),previous};let history=undoSelection;for(let i=1;i<25&&history.previous;i++)history=history.previous;history.previous=null;render();message(text);}
 function chooseCore(id){const next=clone(plan);if(!next.nodes.some(n=>n.id===id))S.toggle(next,id,registry);replaceSelection({...selectionState(),plan:next,coreId:id,target:coreId===id?target:null},nameOf(id)+'을 문항의 중심으로 정했습니다.');}
 function renderRecommendations(result){
  const focus=$('coreFocus');focus.replaceChildren();
  focus.append(el('p',coreId?'이번 문항의 핵심':'핵심 재료를 먼저 정해 보세요.','eyebrow'));
  if(coreId){focus.append(el('h3',nameOf(coreId)),example(C.atoms[coreId]?.example));const release=btn('핵심 지정 해제',()=>{coreId=null;target=null;render();message('재료는 유지하고 핵심 지정만 해제했습니다.');},'text-button');focus.append(release);}
  else focus.append(el('p','위의 핵심 틀로 시작하거나, 재료 카드의 ‘핵심으로’를 누르세요.','muted'));
  const choices=coreId?P.targets(effective(),registry,coreId):[],goals=$('goalOptions');goals.replaceChildren();
  for(const choice of choices){
   const active=target&&P.key(target)===P.key(choice.target),b=btn('',()=>{target=active?null:choice.target;render();$('goalOptions').querySelector('[data-goal="'+CSS.escape(P.key(choice.target))+'"]')?.focus({preventScroll:true});message(target?'마지막 질문을 정했습니다. 필요한 풀이 흐름을 확인하세요.':'질문 선택을 해제했습니다. 마지막에 구할 정보를 다시 고르세요.');},'goal-choice');
   b.dataset.goal=P.key(choice.target);b.setAttribute('aria-pressed',String(Boolean(active)));b.append(el('b',goalName(choice.target.type)),example(C.goals[choice.target.type]?.example),el('small','대상 '+choice.target.subject+' · '+(choice.unused?'남는 재료 '+choice.unused+'개':choice.route.length?'추가 재료 '+choice.route.length+'개':choice.ready?'현재 구성으로 연결됨':'조건 보충 필요')));
   goals.append(b);
  }
  if(!choices.length)goals.append(el('p',coreId?'현재 재료의 연결 조건을 먼저 보충하세요. 전체 재료에서 다음 단계를 직접 고를 수도 있습니다.':'핵심 틀을 고르면 마지막 질문을 선택할 수 있습니다.','muted'));
  $('goalSummary').textContent=target?'선택한 질문: '+goalName(target.type)+' · '+target.subject:'아직 마지막 질문을 고르지 않았습니다.';
  const audit=P.analyze(effective(),registry,coreId,target),review=$('designAudit');review.replaceChildren();review.className='design-audit '+audit.status;
  review.append(el('b',audit.ready?'핵심에서 마지막 질문까지 연결됐습니다.':'제작 전에 확인할 내용'));
  if(!coreId)review.append(el('p','1. 문항의 중심이 될 핵심 재료를 고르세요.'));
  if(!target)review.append(el('p','2. 마지막에 구할 정보를 고르세요.'));
  for(const issue of audit.issues)review.append(el('p',issue));
  if(coreId&&target&&!audit.issues.length&&!audit.ready)review.append(el('p','3. 아래의 풀이 흐름을 담거나, 선택 목록에서 부족한 조건을 보충하세요.'));
  if(audit.ready)review.append(el('p','선택한 재료가 모두 답을 구하는 흐름에 쓰입니다. 실제 수학 풀이와 난도는 생성 후 검토합니다.'));
  if(audit.coreConnected&&audit.unused.length)review.append(btn('쓰이지 않는 재료 빼기',()=>replaceSelection({plan:{...plan,nodes:plan.nodes.filter(n=>!audit.unused.includes(n.id))},disabled:[...disabled],coreId,target},'마지막 질문에 쓰이지 않는 재료를 뺐습니다. 되돌릴 수 있습니다.')));
  const ordered=result.status==='conditional'?P.reorder(effective(),registry):null;
  if(ordered&&JSON.stringify(ordered.nodes)!==JSON.stringify(plan.nodes))review.append(btn('풀이 순서 자동 정리',()=>replaceSelection({plan:{...plan,nodes:ordered.nodes},disabled:[...disabled],coreId,target},'조건을 추가하지 않고 풀이 순서를 정리했습니다.')));
  const list=$('recommendationList');list.replaceChildren();$('recommendationTitle').textContent='03 · 필요한 풀이 흐름';
  const route=target?choices.find(c=>P.key(c.target)===P.key(target)):null;
  if(route?.route.length){
   const card=el('article',null,'recommendation-card goal-route');card.append(el('h4','질문까지 이렇게 이어 가요'));
   const path=el('ol');for(const n of route.route){const step=el('li');step.append(el('b',nameOf(n.id)),example(C.atoms[n.id]?.example,true));path.append(step);}card.append(path);
   const work=route.route.reduce((w,n)=>({algebra:w.algebra+ops.get(n.id).work.algebra,branches:w.branches+ops.get(n.id).work.branches}),{algebra:0,branches:0});
   card.append(el('p','추가 예상 · 식 정리 '+work.algebra+'단위 / 경우 살피기 '+work.branches+'단위','recommendation-work'));
   card.append(btn('이 풀이 흐름 담기',()=>{
    const fresh=P.targets(effective(),registry,coreId).find(c=>P.key(c.target)===P.key(target));
    if(!fresh?.route.length)return message('구성이 바뀌었습니다. 마지막 질문을 다시 확인하세요.');
    replaceSelection({plan:{...plan,nodes:[...plan.nodes,...clone(fresh.route)]},disabled:[...disabled],coreId,target},'마지막 질문에 필요한 재료를 담았습니다. 난도·제작 설정으로 넘어갈 수 있습니다.');$('goToMake').focus({preventScroll:true});
   }));list.append(card);
  }else list.append(el('p',audit.ready?'풀이 흐름이 준비됐습니다. 아래에서 계산 부담과 추론 목표를 정하세요.':target?'현재 등록된 규칙으로 자동 완성할 흐름이 없습니다. 선택 목록에서 조건과 순서를 확인하세요.':'마지막 질문을 고르면 그 질문에 필요한 재료만 제안합니다.','recommendation-empty'));
 }
 function scopedAudit(p){const a=P.analyze(p,registry,coreId,target),u=U.audit(p,registry,unitScope);return {...a,ready:a.ready&&u.valid,issues:[...a.issues,...u.issues]};}
 function scopedRoutes(p){return coreId?PAAuthoring.routes(p,registry,coreId).filter(c=>unitScope&&U.audit({...p,nodes:[...p.nodes,...c.route]},registry,unitScope).valid):[];}
 const unitWorkbench=PAUnitUI.mount($('unitWorkbench'),{initialMode:new URLSearchParams(location.search).get('mode'),change:value=>{replaceSelection({...selectionState(),unitScope:value},'제작 범위를 정했습니다. 기존 재료는 유지하고 연결을 다시 확인합니다.');},continueToMaterials:()=>{mindmap.focusNode('@library');$('mapWorkbench').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}});
 const mindmap=PAAuthoringUI.mount($('mapWorkbench'),{example});
 function renderMap(){
  const p=effective(),audit=scopedAudit(p);
  mindmap.render({registry,plan:p,coreId,target,mapState,unitScope,audit,choices:scopedRoutes(p),repair:S.advice(p,engine),givens:plan.facts.map(f=>({fact:f,enabled:!disabled.has(factKey(f))})),actions:{
   startMaterial:id=>replaceSelection(PABundles.seed(registry,id),'재료와 필요한 시작 정보를 담았습니다. 마지막 질문을 골라 주세요.'),
   addMaterial:item=>{try{const next=PABundles.attach(effective(),registry,item);replaceSelection({...selectionState(),plan:{...plan,nodes:next.nodes}},'기존 정보에 이어지는 재료를 담았습니다. 질문까지의 연결을 확인하세요.');}catch(e){message(e.message);}},
   removeBundle:ids=>replaceSelection({...selectionState(),plan:{...plan,nodes:plan.nodes.filter(n=>!ids.includes(n.id))}},'묶음의 재료를 뺐습니다. 되돌리기로 복구할 수 있어요.'),
   start:id=>replaceSelection(S.coreStart(registry,id),'새 핵심 틀을 준비했습니다. 마지막 질문을 골라 주세요.'),
   toggleFact:fact=>{const next=new Set(disabled),k=factKey(fact);next.has(k)?next.delete(k):next.add(k);replaceSelection({...selectionState(),disabled:[...next]},next.has(k)?'주어진 정보에서 제외했습니다. 풀이 연결을 확인하세요.':'주어진 정보를 다시 포함했습니다.');},
   starters:()=>{$('starterDetails').open=true;$('starterDetails').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('presets').querySelector('button')?.focus({preventScroll:true});},
   chooseQuestion:choice=>{const fresh=scopedRoutes(effective()).find(c=>P.key(c.target)===P.key(choice.target));if(!fresh)return message('현재 구성이 바뀌었습니다. 질문을 다시 고르세요.');replaceSelection({...selectionState(),target:fresh.target},'마지막 질문을 정했습니다. 이 질문에 필요한 생각만 이어 붙여 보세요.');},
   next:(item,focus)=>{const next=PAAuthoring.attach(effective(),registry,coreId,target,item,focus);replaceSelection({...selectionState(),plan:{...plan,nodes:next.nodes}},'질문에 필요한 생각을 붙였습니다. 추가된 풀이를 확인하세요.');},
   complete:()=>{const next=PAAuthoring.complete(effective(),registry,coreId,target);replaceSelection({...selectionState(),plan:{...plan,nodes:next.nodes}},'미리 본 연결을 붙였습니다. 모든 재료가 답에 쓰이는지 확인하세요.');mindmap.focusNode('@review');},
   repair:()=>{const a=S.advice(effective(),engine);if(!a.nodes.length)return message('현재 보충할 연결이 없습니다.');const next=clone(plan);next.nodes.splice(a.at,0,...clone(a.nodes));replaceSelection({...selectionState(),plan:next},'부족했던 정보의 연결을 복구했습니다.');},
   role:(id,role)=>{replaceSelection({...selectionState(),mapState:{...mapState,roles:{...mapState.roles,[id]:role}}},'이번 문항에서 맡길 역할을 바꿨습니다.');$('mapWorkbench').querySelector('[data-role="'+role+'"]')?.focus({preventScroll:true});},
   attach:(from,item,role)=>{try{const added=G.attach(effective(),registry,from,item,role,mapState);replaceSelection({...selectionState(),plan:{...plan,nodes:added.plan.nodes},mapState:added.mapState},'선택한 노드의 정보를 사용하는 재료를 붙였습니다.');mindmap.focusNode(item.id);}catch(e){message(e.message);}},
   goal:choice=>{const fresh=P.targets(effective(),registry,coreId).find(c=>P.key(c.target)===P.key(choice.target));if(!fresh)return message('구성이 바뀌었습니다. 질문을 다시 고르세요.');replaceSelection({...selectionState(),plan:{...plan,nodes:[...plan.nodes,...clone(fresh.route)]},target:fresh.target},'마지막 질문까지 필요한 재료를 연결했습니다.');mindmap.focusNode('@question');},
   remove:id=>replaceSelection({...selectionState(),plan:{...plan,nodes:plan.nodes.filter(n=>n.id!==id)}},'노드를 뺐습니다. 이어진 곳에 부족해진 정보가 있는지 확인하세요.'),
   core:id=>chooseCore(id),
   declare:fact=>{const next=clone(plan);S.declare(next,fact);replaceSelection({...selectionState(),plan:next,disabled:[...disabled].filter(k=>k!==factKey(fact))},'문제에 줄 시작 조건을 추가했습니다.');},
   move:(id,position)=>replaceSelection({...selectionState(),mapState:{...mapState,positions:{...mapState.positions,[id]:position}}},'노드의 위치를 옮겼습니다. 풀이 연결은 유지됩니다.'),
   arrange:()=>replaceSelection({...selectionState(),mapState:{...mapState,positions:{}}},'정보가 이어지는 방향으로 가지를 정리했습니다.'),
   prune:()=>replaceSelection({...selectionState(),plan:{...plan,nodes:plan.nodes.filter(n=>!audit.unused.includes(n.id))}},'현재 질문에 쓰이지 않는 노드를 뺐습니다.'),
   givens:()=>{$('workspaceTools').open=true;$('planDetails').open=true;document.querySelector('.givens-panel').open=true;document.querySelector('.givens-panel').scrollIntoView({block:'center'});},
   produce:()=>$('goToMake').click()
  }});
 }
 function remember(){try{localStorage.setItem('pa-compose-boxes-v1',JSON.stringify({plan,coreId,target,mapState,unitScope,disabled:[...disabled],brief:$('brief').value,calculation,reasoning}));}catch(_){}}
 function acceptPlan(p,core=null,goal=null,view=null,scope=null){if(!p||!Array.isArray(p.nodes)||p.nodes.length>100||p.nodes.some(n=>!ops.has(n.id))||!Array.isArray(p.facts)||p.facts.length>2000||p.facts.some(f=>!registry.types[f.type]))throw Error('알 수 없는 재료나 조건이 있습니다. 구성 파일을 확인하세요.');const next={revision:registry.revision,nodes:clone(p.nodes),facts:clone(p.facts)};const check=engine.run(next);if(check.errors.length)throw Error(check.errors.join(' '));G.compile(next,registry);const nextView=G.state(view,next);if(p.revision!==registry.revision)$('loadStatus').textContent='기존 선택을 유지하고 새 자산 판본으로 연결을 다시 검사했습니다.';unitScope=U.normalize(scope);plan=next;mapState=nextView;disabled.clear();coreId=S.validCore(plan,core);target=goal&&coreId?P.intent(plan,registry,coreId,goal,0,1).target:null;}
 try{const d=JSON.parse(localStorage.getItem('pa-compose-boxes-v1')||'null');if(d){acceptPlan(d.plan,d.coreId,d.target,d.mapState,d.unitScope);disabled=new Set(d.disabled||[]);$('brief').value=d.brief||'';calculation=d.calculation||0;reasoning=d.reasoning??1;}}catch(_){$('loadStatus').textContent='이전 구성의 판본이 달라 새 구성으로 시작했습니다.';}
 if(location.hash.startsWith('#draft=')){try{const d=JSON.parse(decodeURIComponent(location.hash.slice(7)));if(d.schema!=='problem-atom/selection-draft/1')throw Error('선택 구성 오류');if(d.reviewRecords?.length){if(!session.local)throw Error('검수 기록은 연결 도우미에서 가져오세요.');for(const row of d.reviewRecords)PAReviewModel.validate({schema:'problem-atom/group-review/1.0',actor:row.actor,groups:[row]},reviewStore.get().catalog);for(const row of d.reviewRecords){const old=PAReviewModel.current(reviewStore.get().ledger,reviewStore.get().catalog).find(r=>r.groupId===row.groupId);if(!old||row.at>old.at)await reviewStore.save({schema:'problem-atom/group-review/1.0',actor:row.actor,groups:[row]});}reviewStore.attach(registry);}acceptPlan(d.plan,d.coreId,d.target,d.mapState,d.unitScope);$('brief').value=String(d.brief||'').slice(0,5000);calculation=d.calculation||0;reasoning=d.reasoning??1;history.replaceState(null,'',location.pathname);$('loadStatus').textContent='선택한 재료를 연결 도우미로 가져왔습니다.';}catch(e){$('loadStatus').textContent=e.message;}}
 const incomingUnit=new URLSearchParams(location.search).get('unit');if(incomingUnit){if(U.get(incomingUnit))unitScope=U.scope(incomingUnit);else $('loadStatus').textContent='등록되지 않은 대단원입니다. 아래에서 선택하세요.';}
 if(incomingUnit||new URLSearchParams(location.search).has('mode')){const cleanUrl=new URL(location.href);cleanUrl.searchParams.delete('unit');cleanUrl.searchParams.delete('mode');history.replaceState(null,'',cleanUrl.pathname+cleanUrl.search+cleanUrl.hash);}
 if(![0,1,2].includes(calculation))calculation=0;if(![0,1,2].includes(reasoning))reasoning=1;
 function renderChoices(){for(const [host,items,current,set]of [['calculationOptions',calcChoices,calculation,v=>calculation=v],['reasoningOptions',reasonChoices,reasoning,v=>reasoning=v]]){const box=$(host);box.replaceChildren();items.forEach(([name,description],i)=>{const label=el('label',null,'choice-box'),input=el('input');input.type='radio';input.name=host;input.value=String(i);input.checked=current===i;input.onchange=()=>{set(i);remember();};label.append(input,el('b',name),el('small',description));box.append(label);});}}
 function renderFilters(){const host=$('categoryFilters');host.replaceChildren();S.categories.forEach(([key,name])=>{const count=registry.operations.filter(o=>key==='all'||S.category(o)===key).length;const b=btn('',()=>{category=key;renderFilters();renderCards();},'category');b.setAttribute('aria-pressed',String(category===key));b.append(el('span',name),el('small',String(count)));host.append(b);});const sources=$('sourceFilters');sources.replaceChildren();[['','전체'],...Array.from(new Set(registry.records.map(r=>r.origin))).map(o=>[o,originName(o)])].forEach(([value,name])=>{const b=btn(name,()=>{source=value;renderFilters();renderCards();});b.setAttribute('aria-pressed',String(source===value));sources.append(b);});}
 function renderCards(focusId){
  const term=$('search').value.trim().toLowerCase(),selected=new Set(plan.nodes.map(n=>n.id));
  const rows=registry.operations.filter(o=>(category==='all'||S.category(o)===category)&&(!source||origins(o).includes(source))&&(!onlySelected||selected.has(o.id))&&(!term||[o.name,nameOf(o.id),C.atoms[o.id]?.example||'',o.guard_note,...o.requires.map(p=>registry.types[p.type]),...o.provides.map(p=>registry.types[p.type])].join(' ').toLowerCase().includes(term)));
  $('catalogTitle').textContent=S.categories.find(c=>c[0]===category)[1];$('resultCount').textContent=rows.length+'개 재료 · 선택 '+plan.nodes.length+'개';$('showAll').setAttribute('aria-pressed',String(!onlySelected));$('showSelected').setAttribute('aria-pressed',String(onlySelected));
  const host=$('cards');host.replaceChildren();for(const o of rows){
   const checked=selected.has(o.id),card=el('article',null,'atom-card'+(checked?' selected':'')),label=el('label',null,'card-select'),top=el('div',null,'card-top'),input=el('input');
   input.type='checkbox';input.checked=checked;input.dataset.atom=o.id;input.setAttribute('aria-label',nameOf(o.id)+' 선택');input.onchange=()=>{S.toggle(plan,o.id,registry);render(o.id);};
   top.append(el('span',S.categories.find(c=>c[0]===S.category(o))[1],'card-category'),...(coreId===o.id?[el('span','핵심','core-tag')]:[]),input);label.append(top,el('h3',nameOf(o.id)));const description=C.atoms[o.id]?.description||S.describe(o,registry)[0];label.append(el('p',description,'card-desc'),example(C.atoms[o.id]?.example));card.append(label);
   const detail=el('div',null,'card-details');detail.hidden=true;detail.id='detail-'+o.id;detail.append(el('p','얻는 정보: '+o.provides.map(p=>registry.types[p.type]).join(' · ')),el('p','필요한 것: '+o.requires.map(p=>registry.types[p.type]).join(' · ')),el('p',o.guard_note));if(o.forbids.length)detail.append(el('p','함께 쓰면 안 되는 조건: '+o.forbids.map(p=>registry.types[p.type]).join(' · ')));detail.append(el('p','검토 전 자산 · '+o.supports.length+'개 원본 기록 연결'),el('code',o.id));
   const meta=el('div',null,'card-meta'),more=btn('사용 조건',()=>{detail.hidden=!detail.hidden;more.setAttribute('aria-expanded',String(!detail.hidden));});more.setAttribute('aria-expanded','false');more.setAttribute('aria-controls',detail.id);more.setAttribute('aria-label',nameOf(o.id)+' 사용 조건');const setCore=btn(coreId===o.id?'핵심 재료':'핵심으로',()=>chooseCore(o.id));setCore.setAttribute('aria-pressed',String(coreId===o.id));setCore.setAttribute('aria-label',nameOf(o.id)+' 핵심으로');meta.append(setCore,more);card.append(meta,detail);host.append(card);
  }if(!rows.length)host.append(el('p','검색 조건에 맞는 재료가 없습니다. 다른 분류나 검색어를 골라 주세요.','empty-selection'));
  if(focusId)host.querySelector('[data-atom="'+CSS.escape(focusId)+'"]')?.focus({preventScroll:true});
 }
 function renderGivens(){const host=$('givenFacts');host.replaceChildren();$('factCount').textContent=effective().facts.length+'개';for(const f of plan.facts){const l=el('label',null,'given'),input=el('input');input.type='checkbox';input.checked=!disabled.has(factKey(f));input.onchange=()=>{input.checked?disabled.delete(factKey(f)):disabled.add(factKey(f));render();};l.append(input,el('span',registry.types[f.type]+' · '+f.subject+(f.object?' ↔ '+f.object:'')));host.append(l);}if(!plan.facts.length)host.append(el('p','아직 지정한 조건이 없습니다. 필요한 조건은 모델이 제안할 수 있습니다.','muted'));}
 function render(focusId){
  plan.nodes=G.compile(effective(),registry).plan.nodes;mapState=G.state(mapState,plan);
  coreId=S.validCore(plan,coreId);if(!coreId)target=null;if(undoSelection&&undoSelection.after!==signature())undoSelection=null;
  $('undoSelection').disabled=!undoSelection;const empty=!plan.nodes.length&&!plan.facts.length;$('clearPlan').disabled=empty;$('clearAll').disabled=empty;
  const a=S.advice(effective(),engine),result=a.result;renderCards(focusId);renderRecommendations(result);$('selectedCount').textContent=plan.nodes.length;$('dockCount').textContent=plan.nodes.length;$('jumpProduction').disabled=!plan.nodes.length;const host=$('selectedNodes');host.replaceChildren();
  plan.nodes.forEach((node,i)=>{const op=ops.get(node.id),li=el('li',null,'selected-node'),title=el('div',null,'selected-title');title.append(el('span',coreId===node.id?'핵심':String(i+1),'node-number'+(coreId===node.id?' is-core':'')),el('h3',nameOf(node.id)));li.append(title);const controls=el('div',null,'selected-tools');
   const up=btn('↑',()=>{[plan.nodes[i-1],plan.nodes[i]]=[plan.nodes[i],plan.nodes[i-1]];render();});up.disabled=i===0;up.setAttribute('aria-label',nameOf(node.id)+' 위로');
   const down=btn('↓',()=>{[plan.nodes[i+1],plan.nodes[i]]=[plan.nodes[i],plan.nodes[i+1]];render();});down.disabled=i===plan.nodes.length-1;down.setAttribute('aria-label',nameOf(node.id)+' 아래로');const remove=btn('빼기',()=>{plan.nodes.splice(i,1);render();},'remove');remove.setAttribute('aria-label',nameOf(node.id)+' 빼기');const setCore=btn(coreId===node.id?'핵심':'핵심으로',()=>chooseCore(node.id),'core-control');setCore.setAttribute('aria-pressed',String(coreId===node.id));setCore.setAttribute('aria-label',nameOf(node.id)+' 핵심으로');controls.append(setCore,remove);li.append(controls);
   const details=el('details');details.append(el('summary','예시·대상 설정'),example(C.atoms[node.id]?.example,true));const fields=el('div',null,'binding-fields');const slots=[...new Set([...op.requires,...op.provides,...op.forbids].flatMap(p=>[p.subject,p.object].filter(Boolean).map(v=>v.slice(1))))];
   slots.forEach(slot=>{const l=el('label',slot==='f'?'다룰 함수':slot==='h'?'변환한 함수':'매개변수'),input=el('input');input.value=node.bindings[slot]||'';input.maxLength=100;input.onchange=()=>{node.bindings[slot]=input.value.trim();render();};l.append(input);fields.append(l);});const l=el('label','가정 범위'),input=el('input');input.value=node.scope;input.maxLength=100;input.onchange=()=>{node.scope=input.value.trim();render();};l.append(input);fields.append(l);details.append(fields);li.append(details);host.append(li);
  });if(!plan.nodes.length)host.append(el('li','왼쪽 카드의 체크박스를 눌러 재료를 담아 주세요.','empty-selection'));
  const verdict=$('connectionStatus');verdict.hidden=!plan.nodes.length;verdict.className=result.status;verdict.textContent=result.status==='connected'?'연결 조건이 갖춰졌습니다. 실제 문항은 별도 검산합니다.':result.status==='blocked'?'충돌하는 조건이 있습니다. 대상을 확인해 주세요.':'조건을 보충하거나 이어 주는 요소가 필요합니다.';
  const suggestions=$('suggestions');suggestions.replaceChildren();
  if(a.nodes.length){const box=el('div',null,'suggestion');box.append(el('b','사이에 넣으면 연결되는 재료'),el('p',a.nodes.map(n=>nameOf(n.id)).join(' → ')),btn('추천 연결 '+a.nodes.length+'개 넣기',()=>{plan.nodes.splice(a.at,0,...clone(a.nodes));render();}));suggestions.append(box);}
  if(!a.nodes.length&&a.missing.length){const d=el('details');d.append(el('summary','필요한 조건 '+a.missing.length+'개 확인'));a.missing.forEach(f=>{const row=el('div',null,'missing-fact');row.append(el('span',registry.types[f.type]+' · '+f.subject),btn('조건으로 주기',()=>{S.declare(plan,f);disabled.delete(factKey(f));render();}));d.append(row);});suggestions.append(d);}
  if(result.errors.length)suggestions.append(el('p',result.errors.join(' '),'muted'));for(const t of result.trace.filter(t=>t.status==='blocked'))suggestions.append(el('p',t.reasons.join(' '),'muted'));
  const audit=scopedAudit(effective());
  $('workPreview').textContent=plan.nodes.length?'답으로 이어지는 풀이 '+audit.steps+'단계 · 식 정리 '+audit.work.algebra+'단위 · 경우 살피기 '+audit.work.branches+'단위':'재료를 고르면 확인할 수 있어요.';
  unitWorkbench.render({scope:unitScope,registry,plan:effective()});$('workspace').hidden=!unitScope;$('production').hidden=!unitScope;$('unitFirstNote').hidden=!!unitScope;$('creationFlow').hidden=!unitScope;renderMap();$('starterDetails').open=!plan.nodes.length;$('goToMake').disabled=!audit.ready;$('jumpProduction').disabled=!audit.ready;$('generate').disabled=busy||!audit.ready;renderGivens();remember();
 }
 function renderConditionBoxes(){const host=$('conditionBoxes'),term=$('conditionSearch').value.trim();host.replaceChildren();for(const [type,name]of Object.entries(registry.types).filter(([k,v])=>v.includes(term)||k.includes(term)||(C.facts[k]||'').includes(term))){const b=btn('',()=>{const subject=$('conditionSubject').value.trim(),scope=$('conditionScope').value.trim();if(!subject||!scope)return;const f={type,subject,scope,origin:'given'};if(type==='height_identity')f.object=$('conditionObject').value.trim();if(type==='height_identity'&&!f.object)return;S.declare(plan,f);disabled.delete(factKey(f));render();renderConditionBoxes();},'condition-box');b.append(el('b',name),example(C.facts[type]));b.setAttribute('aria-pressed',String(plan.facts.some(f=>f.type===type&&f.subject===$('conditionSubject').value.trim()&&!disabled.has(factKey(f)))));host.append(b);}if(!host.children.length)host.append(el('p','찾는 조건이 없습니다. 다른 이름이나 예시 속 단어로 검색해 보세요.','muted'));}
 S.coreStarts.forEach(start=>{const seed=S.coreStart(registry,start.id),b=btn('',()=>replaceSelection(seed,'핵심 틀을 담았습니다. 추천 재료를 하나씩 붙여 보세요.'),'preset');b.append(el('b',C.starts[start.id]?.name||start.name),example(C.starts[start.id]?.example),el('small','핵심 포함 '+seed.plan.nodes.length+'개 재료 · 시작 조건 '+seed.plan.facts.length+'개'));$('presets').append(b);});
 $('search').oninput=()=>renderCards();$('showAll').onclick=()=>{onlySelected=false;renderCards();};$('showSelected').onclick=()=>{onlySelected=true;renderCards();};const clear=()=>replaceSelection(S.clearSelection(selectionState(),registry),'모든 재료와 시작 조건을 해제했습니다. 되돌리기로 복구할 수 있습니다.');
 $('clearPlan').onclick=clear;$('clearAll').onclick=clear;
 $('undoSelection').onclick=()=>{if(!undoSelection)return;const previous=undoSelection.before;undoSelection=undoSelection.previous||null;plan=previous.plan;disabled=new Set(previous.disabled);coreId=previous.coreId;target=previous.target;unitScope=U.normalize(previous.unitScope);mapState=previous.mapState||{roles:{},positions:{}};render();message('이전 재료와 시작 조건을 복구했습니다.');};
 $('jumpSelection').onclick=()=>{document.querySelector('.selection-panel').scrollIntoView({block:'start'});$('selectionTitle').setAttribute('tabindex','-1');$('selectionTitle').focus({preventScroll:true});};$('jumpProduction').onclick=()=>$('goToMake').click();
 $('addCondition').onclick=()=>{renderConditionBoxes();$('conditionDialog').showModal();$('conditionSearch').focus();};$('closeConditions').onclick=()=>$('conditionDialog').close();$('conditionSearch').oninput=renderConditionBoxes;for(const id of ['conditionSubject','conditionScope'])$(id).oninput=renderConditionBoxes;
 $('goToMake').onclick=()=>{$('production').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});$('productionTitle').setAttribute('tabindex','-1');$('productionTitle').focus({preventScroll:true});};
 $('savePlan').onclick=()=>save({schema:'problem-atom/connection-plan/1',...effective(),coreId,target,mapState,unitScope},'문항_재료_구성.json');$('loadPlanButton').onclick=()=>$('importPlan').click();
 async function fileValue(input){const file=input.files[0];if(!file)return null;if(file.size>2000000)throw Error('2MB 이하 JSON 파일만 열 수 있습니다.');return JSON.parse(await file.text());}
 $('importPlan').onchange=async()=>{try{const value=await fileValue($('importPlan'));if(!value)return;if(value.schema!=='problem-atom/connection-plan/1')throw Error('구성 파일이 아닙니다.');acceptPlan(value,value.coreId,value.target,value.mapState,value.unitScope);render();message('저장한 구성을 불러왔습니다.');}catch(e){message(e.message);}};
 function request(){const p=effective();if(reviewLoadError)throw Error('검수 기록을 확인하지 못했습니다. '+reviewLoadError);if(!scopedAudit(p).ready)throw Error('재료와 마지막 질문을 고르고 풀이 흐름을 완성하세요.');return PAModelContract.makeRequest(registry,p,'선택한 재료를 실제로 함께 사용하는 고등학교 수학 문항 한 개를 제작하세요. 필요한 조건과 가교를 보완하되 선택한 생각을 장식으로 붙이지 마세요.\n계산 부담: '+calcChoices[calculation].join(' — ')+'\n목표 추론 난도(제작 목표이며 실제 난도 보장 아님): '+reasonChoices[reasoning].join(' — ')+'\n'+PABundles.instruction(p,registry,coreId)+'\n'+$('brief').value,'REQ-'+crypto.randomUUID(),{...P.intent(p,registry,coreId,target,calculation,reasoning,G.spec(p,registry,mapState)),core_role:'connection_anchor',curriculum_scope:U.normalize(unitScope)});}
 function generationStatus(text){$('generationStatus').textContent=text;}
 $('brief').oninput=remember;
 $('saveRequest').onclick=()=>{try{pending=request();save(pending,'제작요청_'+pending.request_id+'.json');generationStatus('요청 파일을 저장했습니다. 이 번호에 맞는 결과를 불러올 수 있습니다.');}catch(e){generationStatus(e.message);}};
 $('savePrompt').onclick=async()=>{try{pending=request();await navigator.clipboard.writeText(PAModelContract.handoff(pending));generationStatus('현재 Codex 대화에 붙여 넣을 제작 요청을 복사했습니다.');}catch(e){generationStatus(e.message);}};
 $('importRequest').onchange=async()=>{try{if(busy)throw Error('진행 중인 제작이 끝난 뒤 다른 요청을 열어 주세요.');const v=await fileValue($('importRequest'));if(!v)return;if(v.schema!=='problem-atom/model-request/1'||v.registry_revision!==registry.revision)throw Error('요청 형식 또는 자산 판본이 다릅니다.');pending=PAModelContract.makeRequest(registry,v.seed_plan,v.brief,v.request_id,v.design_intent);acceptPlan(v.seed_plan,v.design_intent?.core.id,v.design_intent?.target,{roles:Object.fromEntries((v.design_intent?.graph?.roles||[]).map(r=>[r.id,r.role]))},v.design_intent?.curriculum_scope);if(v.design_intent){calculation=v.design_intent.calculation;reasoning=v.design_intent.reasoning;renderChoices();}render();generationStatus('제작 요청을 열었습니다. 같은 번호의 결과를 검사할 수 있습니다.');}catch(e){generationStatus(e.message);}};
 function showResult(output,job=pending){if(!job)throw Error('해당 문항의 제작 요청 파일을 먼저 열어 주세요.');const data=output.result||output,v=PAModelContract.validateResult(data,job,registry,engine),host=$('modelResult');host.replaceChildren();$('reviewBadge').textContent='독립 검산 대기';const notice=el('p',v.accepted?job.design_intent?'설계 목표·연결 검사 통과 · 독립 수학 검산 대기':'형식·연결 검사 통과 · 수학 검산과 사람 검토 대기':'수정할 내용이 있습니다 · 아직 출제할 수 없습니다.','result-notice'+(v.accepted?' passed':''));host.append(notice);if(v.errors.length){const ul=el('ul',null,'result-errors');v.errors.forEach(e=>ul.append(el('li',e)));host.append(ul);}if(PAModelContract.schemaErrors(data,PAModelContract.RESULT_SCHEMA).length)return;host.append(el('h3',data.title));data.question.forEach(t=>host.append(math(t)));
  const details=(name,lines)=>{const d=el('details');d.append(el('summary',name));lines.forEach(t=>d.append(math(t)));host.append(d);};details('정답과 풀이',[data.answer,...data.solution]);details('각 조건을 넣은 이유',data.condition_roles.map(c=>c.condition+' → '+c.used_in+' / 빼면: '+c.removal_effect));details('실제 풀이의 계산과 추론',[data.work_estimate.calculation,data.work_estimate.reasoning,data.work_estimate.bottleneck]);details('사용한 재료',data.plan.nodes.map(n=>nameOf(n.id)+' · '+n.scope));details('모델 자체 점검 · 독립 검산 아님',data.self_checks.map(c=>c.check+': '+c.result));if(data.new_bridge_proposals.length)details('새 연결 제안 · 검토 전',data.new_bridge_proposals.map(p=>p.name+': '+p.mathematical_argument));host.append(btn('문항과 풀이 저장',()=>save({request:job,result:data,validation:v},'제작결과_'+job.request_id+'.json')));if(v.accepted)host.append(btn('한글 출력에 담기',()=>{try{productionIO.add({request:job,result:data});$('printWorkbench').scrollIntoView({block:'start'});}catch(e){generationStatus(e.message);}},'primary'));}
 $('importResult').onchange=async()=>{try{if(busy)throw Error('제작이 끝난 뒤 다른 결과를 열어 주세요.');const data=await fileValue($('importResult'));if(data){const own=data.request?PAWebHandoff.canonicalRequest(data.request,registry):pending;showResult(data,own);}}catch(e){generationStatus(e.message);}};
 $('connectSession').onclick=async()=>{if(session.local){await checkSession();generationStatus(sessionReady?'Codex 로그인 연결을 확인했습니다. 재료를 골라 제작하세요.':'Codex 로그인 또는 연결 도우미 상태를 확인하세요.');}else $('sessionDialog').showModal();};$('closeSession').onclick=()=>$('sessionDialog').close();$('openCompanion').onclick=()=>{session.open(effective(),$('brief').value,calculation,reasoning,coreId,target,mapState,unitScope,PAReviewModel.current(reviewStore.get().ledger,reviewStore.get().catalog));$('sessionDialog').close();};
 async function checkSession(){if(!session.local){productionIO?.capabilities(null);$('sessionBadge').textContent='Codex 연결';$('sessionDescription').textContent='API 키 없이 Codex 로그인으로 제작합니다. 먼저 이 PC의 연결 도우미 화면을 열어 주세요.';return;}try{const s=await session.status();productionIO?.capabilities(s);sessionReady=s.ready&&s.revision===registry.revision&&s.design_intent_version===1&&s.reasoning_graph_version===1&&s.authoring_blueprint_version===1&&s.judgment_bundle_version===1&&s.curriculum_scope_version===1;$('sessionBadge').textContent=sessionReady?'Codex 연결됨 · Sol':(s.design_intent_version!==1||s.reasoning_graph_version!==1||s.authoring_blueprint_version!==1||s.judgment_bundle_version!==1||s.curriculum_scope_version!==1)?'도우미 재시작 필요':'로그인 확인 필요';$('connectSession').classList.toggle('connected',sessionReady);$('sessionDescription').textContent=(s.revision!==registry.revision||s.design_intent_version!==1||s.reasoning_graph_version!==1||s.authoring_blueprint_version!==1||s.judgment_bundle_version!==1||s.curriculum_scope_version!==1)?'화면과 연결 도우미의 버전이 다릅니다. 도우미를 다시 시작하세요.':s.reason+' · Codex 이용 한도를 사용합니다.';if(s.activeJob&&!activeJob){activeJob=s.activeJob;busy=true;poll();}}catch(e){sessionReady=false;$('sessionBadge').textContent='연결 끊김';$('sessionDescription').textContent=e.message;}}
 async function historyList(){if(!session.local)return;try{const response=await session.jobs(),host=$('jobHistory');host.replaceChildren();if(!response.jobs.length)host.append(el('p','아직 제작 기록이 없습니다.','muted'));for(const j of response.jobs){const row=el('div',null,'job-row');row.append(el('span',new Date(j.createdAt).toLocaleString('ko-KR')+' · '+({running:'제작 중',completed:'결과 도착',failed:'실패',cancelled:'취소',interrupted:'중단'}[j.status]||j.status)),btn('열기',async()=>{try{const full=await session.job(j.id);pending=full.request;if(full.output)showResult(full.output,full.request);else generationStatus(full.message);if(full.status==='running'){activeJob=full.id;busy=true;poll();}}catch(e){generationStatus(e.message);}}));host.append(row);}}catch(e){$('jobHistory').textContent=e.message;}}
 async function poll(){clearTimeout(pollTimer);if(!activeJob)return;try{const j=await session.job(activeJob);pending=j.request;const elapsed=Math.max(0,Math.floor((Date.now()-Date.parse(j.createdAt))/1000));generationStatus(j.message+(j.status==='running'?' · '+Math.floor(elapsed/60)+'분 '+elapsed%60+'초 경과':''));if(j.status==='running'){busy=true;$('cancelJob').hidden=false;$('generate').disabled=true;pollTimer=setTimeout(poll,2000);}else{busy=false;activeJob=null;$('cancelJob').hidden=true;if(j.output)showResult(j.output,j.request);render();historyList();}}catch(e){generationStatus(e.message+' 제작 기록에서 완료 여부를 확인하세요.');busy=false;$('cancelJob').hidden=true;render();}}
 $('generate').onclick=async()=>{if(busy)return;if(!session.local){$('sessionDialog').showModal();return;}try{if(!sessionReady)await checkSession();if(!sessionReady)throw Error($('sessionDescription').textContent||'Codex에서 ChatGPT 로그인 상태를 확인하세요.');if(!await refreshReviews())throw Error(reviewLoadError);pending=request();busy=true;render();generationStatus('선택한 원자를 Codex Sol에 전달하고 있습니다.');const j=await session.submit(pending);activeJob=j.id;poll();}catch(e){busy=false;render();generationStatus(e.message);}};
 $('cancelJob').onclick=async()=>{try{if(activeJob){await session.cancel(activeJob);generationStatus('취소를 요청했습니다.');poll();}}catch(e){generationStatus(e.message);}};
 productionIO=PAProductionIO.mount({registry,session,request,showResult});
 $('assetCount').textContent='연결 재료 '+registry.operations.length+'개 · 원본 '+registry.records.length+'개';renderFilters();renderChoices();render();
 const reviewedId=new URLSearchParams(location.search).get('reviewed');
 if(reviewedId&&ops.has(reviewedId)){if(!unitScope&&!plan.nodes.length){unitScope=U.scope(U.classifications[reviewedId]?.main[0]||'m2-integrals');render();}if(unitScope&&U.material(registry,[reviewedId],unitScope).visible)mindmap.focusNode('@preview:'+reviewedId);else message('이 검수 박스는 현재 제작 범위 밖입니다. 제작 틀을 바꾸면 선택할 수 있습니다.');}
 const reviewRefresh=async()=>{if(await refreshReviews())render();else message('검수 기록을 불러오지 못했습니다. '+reviewLoadError);};
 window.addEventListener('focus',reviewRefresh);window.addEventListener('storage',e=>{if(e.key===reviewStore.key)reviewRefresh();});
 await checkSession();await historyList();if(!$('loadStatus').textContent)$('loadStatus').textContent='선택한 재료와 목표는 이 브라우저에 자동 저장됩니다.';
}catch(e){$('loadStatus').textContent='제작실을 열지 못했습니다: '+e.message;}
})();
