(async()=>{'use strict';
const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;};
const btn=(text,fn,cls)=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;};
const clone=x=>structuredClone(x),factKey=f=>JSON.stringify([f.type,f.subject,f.object||null,f.scope]);
function save(value,name,type='application/json'){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function math(text){const p=el('p'),pattern=/\$\$([\s\S]+?)\$\$|\$([^$\n]+?)\$/g;let at=0;for(const m of text.matchAll(pattern)){p.append(document.createTextNode(text.slice(at,m.index)));const span=el('span');katex.render(m[1]||m[2],span,{displayMode:Boolean(m[1]),throwOnError:false,trust:false,maxExpand:1000});p.append(span);at=m.index+m[0].length;}p.append(document.createTextNode(text.slice(at)));return p;}
try{
 const response=await fetch('connection-registry.json',{cache:'no-store'});if(!response.ok)throw Error('자산을 읽지 못했습니다.');
 const registry=await response.json(),engine=PAConnections.create(registry),ops=new Map(registry.operations.map(o=>[o.id,o])),session=PASession.create(),S=PASelection;
 let plan=S.blank(registry),disabled=new Set(),category='all',source='',onlySelected=false,calculation=0,reasoning=1,pending=null,activeJob=null,pollTimer=null,busy=false,sessionReady=false;
 const origins=op=>[...new Set(registry.records.filter(r=>op.supports.includes(r.id)).map(r=>r.origin))];
 const originName=o=>o==='seminar-01'?'1차 세미나':o==='seminar-02'?'2차 세미나':o==='shared'?'공유 자산':o;
 const calcChoices=[['가볍게','전개와 큰 수 계산 줄이기'],['적당히','핵심 식을 세운 뒤 계산'],['충분히','여러 단계 계산 허용']];
 const reasonChoices=[['바로 적용','배운 방법을 찾아 적용'],['생각 연결','두 가지 생각을 이어 풀기'],['관계 발견','숨은 관계와 경우 찾아내기']];
 const effective=()=>({...clone(plan),facts:plan.facts.filter(f=>!disabled.has(factKey(f))).map(clone)});
 function message(t){$('selectionMessage').textContent=t;}
 function remember(){try{localStorage.setItem('pa-compose-boxes-v1',JSON.stringify({plan,disabled:[...disabled],brief:$('brief').value,calculation,reasoning}));}catch(_){}}
 function acceptPlan(p){if(!p||!Array.isArray(p.nodes)||p.nodes.length>100||p.nodes.some(n=>!ops.has(n.id))||!Array.isArray(p.facts)||p.facts.length>2000||p.facts.some(f=>!registry.types[f.type]))throw Error('알 수 없는 재료나 조건이 있습니다. 구성 파일을 확인하세요.');const next={revision:registry.revision,nodes:clone(p.nodes),facts:clone(p.facts)};const check=engine.run(next);if(check.errors.length)throw Error(check.errors.join(' '));if(p.revision!==registry.revision)$('loadStatus').textContent='기존 선택을 유지하고 새 자산 판본으로 연결을 다시 검사했습니다.';plan=next;disabled.clear();}
 try{const d=JSON.parse(localStorage.getItem('pa-compose-boxes-v1')||'null');if(d){acceptPlan(d.plan);disabled=new Set(d.disabled||[]);$('brief').value=d.brief||'';calculation=d.calculation||0;reasoning=d.reasoning??1;}}catch(_){$('loadStatus').textContent='이전 구성의 판본이 달라 새 구성으로 시작했습니다.';}
 if(location.hash.startsWith('#draft=')){try{const d=JSON.parse(decodeURIComponent(location.hash.slice(7)));if(d.schema!=='problem-atom/selection-draft/1')throw Error('선택 구성 오류');acceptPlan(d.plan);$('brief').value=String(d.brief||'').slice(0,5000);calculation=d.calculation||0;reasoning=d.reasoning??1;history.replaceState(null,'',location.pathname);$('loadStatus').textContent='선택한 재료를 연결 도우미로 가져왔습니다.';}catch(e){$('loadStatus').textContent=e.message;}}
 if(![0,1,2].includes(calculation))calculation=0;if(![0,1,2].includes(reasoning))reasoning=1;
 function renderChoices(){for(const [host,items,current,set]of [['calculationOptions',calcChoices,calculation,v=>calculation=v],['reasoningOptions',reasonChoices,reasoning,v=>reasoning=v]]){const box=$(host);box.replaceChildren();items.forEach(([name,description],i)=>{const label=el('label',null,'choice-box'),input=el('input');input.type='radio';input.name=host;input.value=String(i);input.checked=current===i;input.onchange=()=>{set(i);remember();};label.append(input,el('b',name),el('small',description));box.append(label);});}}
 function renderFilters(){const host=$('categoryFilters');host.replaceChildren();S.categories.forEach(([key,name])=>{const count=registry.operations.filter(o=>key==='all'||S.category(o)===key).length;const b=btn('',()=>{category=key;renderFilters();renderCards();},'category');b.setAttribute('aria-pressed',String(category===key));b.append(el('span',name),el('small',String(count)));host.append(b);});const sources=$('sourceFilters');sources.replaceChildren();[['','전체'],...Array.from(new Set(registry.records.map(r=>r.origin))).map(o=>[o,originName(o)])].forEach(([value,name])=>{const b=btn(name,()=>{source=value;renderFilters();renderCards();});b.setAttribute('aria-pressed',String(source===value));sources.append(b);});}
 function renderCards(focusId){
  const term=$('search').value.trim().toLowerCase(),selected=new Set(plan.nodes.map(n=>n.id));
  const rows=registry.operations.filter(o=>(category==='all'||S.category(o)===category)&&(!source||origins(o).includes(source))&&(!onlySelected||selected.has(o.id))&&(!term||[o.name,o.guard_note,...o.requires.map(p=>registry.types[p.type]),...o.provides.map(p=>registry.types[p.type])].join(' ').toLowerCase().includes(term)));
  $('catalogTitle').textContent=S.categories.find(c=>c[0]===category)[1];$('resultCount').textContent=rows.length+'개 재료 · 선택 '+plan.nodes.length+'개';$('showAll').setAttribute('aria-pressed',String(!onlySelected));$('showSelected').setAttribute('aria-pressed',String(onlySelected));
  const host=$('cards');host.replaceChildren();for(const o of rows){
   const checked=selected.has(o.id),card=el('article',null,'atom-card'+(checked?' selected':'')),label=el('label',null,'card-select'),top=el('div',null,'card-top'),input=el('input');
   input.type='checkbox';input.checked=checked;input.dataset.atom=o.id;input.setAttribute('aria-label',o.name+' 선택');input.onchange=()=>{S.toggle(plan,o.id,registry);render(o.id);};
   top.append(el('span',S.categories.find(c=>c[0]===S.category(o))[1],'card-category'),input);label.append(top,el('h3',o.name));const [description,formula]=S.describe(o,registry);label.append(el('p',description,'card-desc'));
   if(formula){const pv=el('div',null,'card-preview');katex.render(formula,pv,{throwOnError:false,displayMode:true,trust:false});label.append(pv);}
   label.append(el('p','얻는 정보 · '+registry.types[o.provides[0].type],'card-result'));card.append(label);
   const detail=el('div',null,'card-details');detail.hidden=true;detail.id='detail-'+o.id;detail.append(el('p','필요한 것: '+o.requires.map(p=>registry.types[p.type]).join(' · ')),el('p',o.guard_note));if(o.forbids.length)detail.append(el('p','함께 쓰면 안 되는 조건: '+o.forbids.map(p=>registry.types[p.type]).join(' · ')));detail.append(el('p','검토 전 자산 · '+o.supports.length+'개 원본 기록 연결'),el('code',o.id));
   const meta=el('div',null,'card-meta'),more=btn('사용 조건',()=>{detail.hidden=!detail.hidden;more.setAttribute('aria-expanded',String(!detail.hidden));});more.setAttribute('aria-expanded','false');more.setAttribute('aria-controls',detail.id);more.setAttribute('aria-label',o.name+' 사용 조건');meta.append(el('span',origins(o).map(originName).join(' · ')),more);card.append(meta,detail);host.append(card);
  }if(!rows.length)host.append(el('p','검색 조건에 맞는 재료가 없습니다. 다른 분류나 검색어를 골라 주세요.','empty-selection'));
  if(focusId)host.querySelector('[data-atom="'+CSS.escape(focusId)+'"]')?.focus({preventScroll:true});
 }
 function renderGivens(){const host=$('givenFacts');host.replaceChildren();$('factCount').textContent=effective().facts.length+'개';for(const f of plan.facts){const l=el('label',null,'given'),input=el('input');input.type='checkbox';input.checked=!disabled.has(factKey(f));input.onchange=()=>{input.checked?disabled.delete(factKey(f)):disabled.add(factKey(f));render();};l.append(input,el('span',registry.types[f.type]+' · '+f.subject+(f.object?' ↔ '+f.object:'')));host.append(l);}if(!plan.facts.length)host.append(el('p','아직 지정한 조건이 없습니다. 필요한 조건은 모델이 제안할 수 있습니다.','muted'));}
 function render(focusId){
  const a=S.advice(effective(),engine),result=a.result;renderCards(focusId);$('selectedCount').textContent=plan.nodes.length;$('dockCount').textContent=plan.nodes.length;$('jumpProduction').disabled=!plan.nodes.length;const host=$('selectedNodes');host.replaceChildren();
  plan.nodes.forEach((node,i)=>{const op=ops.get(node.id),li=el('li',null,'selected-node'),title=el('div',null,'selected-title');title.append(el('span',String(i+1),'node-number'),el('h3',op.name));li.append(title);const controls=el('div',null,'selected-tools');
   const up=btn('↑',()=>{[plan.nodes[i-1],plan.nodes[i]]=[plan.nodes[i],plan.nodes[i-1]];render();});up.disabled=i===0;up.setAttribute('aria-label',op.name+' 위로');
   const down=btn('↓',()=>{[plan.nodes[i+1],plan.nodes[i]]=[plan.nodes[i],plan.nodes[i+1]];render();});down.disabled=i===plan.nodes.length-1;down.setAttribute('aria-label',op.name+' 아래로');const remove=btn('빼기',()=>{plan.nodes.splice(i,1);render();},'remove');remove.setAttribute('aria-label',op.name+' 빼기');controls.append(up,down,remove);li.append(controls);
   const details=el('details');details.append(el('summary','대상·순서 세부 설정'));const fields=el('div',null,'binding-fields');const slots=[...new Set([...op.requires,...op.provides,...op.forbids].flatMap(p=>[p.subject,p.object].filter(Boolean).map(v=>v.slice(1))))];
   slots.forEach(slot=>{const l=el('label',slot==='f'?'다룰 함수':slot==='h'?'변환한 함수':'매개변수'),input=el('input');input.value=node.bindings[slot]||'';input.maxLength=100;input.onchange=()=>{node.bindings[slot]=input.value.trim();render();};l.append(input);fields.append(l);});const l=el('label','가정 범위'),input=el('input');input.value=node.scope;input.maxLength=100;input.onchange=()=>{node.scope=input.value.trim();render();};l.append(input);fields.append(l);details.append(fields);li.append(details);host.append(li);
  });if(!plan.nodes.length)host.append(el('li','왼쪽 카드의 체크박스를 눌러 재료를 담아 주세요.','empty-selection'));
  const verdict=$('connectionStatus');verdict.hidden=!plan.nodes.length;verdict.className=result.status;verdict.textContent=result.status==='connected'?'연결 조건이 갖춰졌습니다. 실제 문항은 별도 검산합니다.':result.status==='blocked'?'충돌하는 조건이 있습니다. 대상을 확인해 주세요.':'조건을 보충하거나 이어 주는 요소가 필요합니다.';
  const suggestions=$('suggestions');suggestions.replaceChildren();
  if(a.nodes.length){const box=el('div',null,'suggestion');box.append(el('b','사이에 넣으면 연결되는 재료'),el('p',a.nodes.map(n=>ops.get(n.id).name).join(' → ')),btn('추천 연결 '+a.nodes.length+'개 넣기',()=>{plan.nodes.splice(a.at,0,...clone(a.nodes));render();}));suggestions.append(box);}
  if(!a.nodes.length&&a.missing.length){const d=el('details');d.append(el('summary','필요한 조건 '+a.missing.length+'개 확인'));a.missing.forEach(f=>{const row=el('div',null,'missing-fact');row.append(el('span',registry.types[f.type]+' · '+f.subject),btn('조건으로 주기',()=>{S.declare(plan,f);disabled.delete(factKey(f));render();}));d.append(row);});suggestions.append(d);}
  if(result.errors.length)suggestions.append(el('p',result.errors.join(' '),'muted'));for(const t of result.trace.filter(t=>t.status==='blocked'))suggestions.append(el('p',t.reasons.join(' '),'muted'));
  const selectedOps=[...new Set(plan.nodes.map(n=>n.id))].map(id=>ops.get(id));const algebra=selectedOps.reduce((n,o)=>n+o.work.algebra,0),branches=selectedOps.reduce((n,o)=>n+o.work.branches,0);
  $('workPreview').textContent=plan.nodes.length?'식 정리 '+algebra+'단위 · 경우 살피기 '+branches+'단위':'재료를 고르면 확인할 수 있어요.';$('goToMake').disabled=!plan.nodes.length;$('generate').disabled=busy||!plan.nodes.length||result.status==='blocked';renderGivens();remember();
 }
 function renderConditionBoxes(){const host=$('conditionBoxes'),term=$('conditionSearch').value.trim();host.replaceChildren();for(const [type,name]of Object.entries(registry.types).filter(([k,v])=>v.includes(term)||k.includes(term))){const b=btn(name,()=>{const subject=$('conditionSubject').value.trim(),scope=$('conditionScope').value.trim();if(!subject||!scope)return;const f={type,subject,scope,origin:'given'};if(type==='height_identity')f.object=$('conditionObject').value.trim();if(type==='height_identity'&&!f.object)return;S.declare(plan,f);disabled.delete(factKey(f));render();renderConditionBoxes();},'condition-box');b.setAttribute('aria-pressed',String(plan.facts.some(f=>f.type===type&&f.subject===$('conditionSubject').value.trim()&&!disabled.has(factKey(f)))));host.append(b);}}
 registry.presets.forEach((p,i)=>{const b=btn('',()=>{plan=S.preset(registry,p.id);disabled.clear();render();message('시작 구성과 필요한 연결을 함께 담았습니다. 카드에서 자유롭게 바꿔 보세요.');},'preset');b.append(el('span',p.name),el('small',['4개 재료','5개 재료','5개 재료'][i]||'시작 구성'));$('presets').append(b);});
 $('search').oninput=()=>renderCards();$('showAll').onclick=()=>{onlySelected=false;renderCards();};$('showSelected').onclick=()=>{onlySelected=true;renderCards();};$('clearPlan').onclick=()=>{plan=S.blank(registry);disabled.clear();render();message('선택한 재료와 시작 조건을 비웠습니다.');};
 $('jumpSelection').onclick=()=>{document.querySelector('.selection-panel').scrollIntoView({block:'start'});$('selectionTitle').setAttribute('tabindex','-1');$('selectionTitle').focus({preventScroll:true});};$('jumpProduction').onclick=()=>$('goToMake').click();
 $('addCondition').onclick=()=>{renderConditionBoxes();$('conditionDialog').showModal();$('conditionSearch').focus();};$('closeConditions').onclick=()=>$('conditionDialog').close();$('conditionSearch').oninput=renderConditionBoxes;for(const id of ['conditionSubject','conditionScope'])$(id).oninput=renderConditionBoxes;
 $('goToMake').onclick=()=>{$('production').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});$('productionTitle').setAttribute('tabindex','-1');$('productionTitle').focus({preventScroll:true});};
 $('savePlan').onclick=()=>save({schema:'problem-atom/connection-plan/1',...effective()},'문항_재료_구성.json');$('loadPlanButton').onclick=()=>$('importPlan').click();
 async function fileValue(input){const file=input.files[0];if(!file)return null;if(file.size>2000000)throw Error('2MB 이하 JSON 파일만 열 수 있습니다.');return JSON.parse(await file.text());}
 $('importPlan').onchange=async()=>{try{const value=await fileValue($('importPlan'));if(!value)return;if(value.schema!=='problem-atom/connection-plan/1')throw Error('구성 파일이 아닙니다.');acceptPlan(value);render();message('저장한 구성을 불러왔습니다.');}catch(e){message(e.message);}};
 function request(){const p=effective();if(engine.run(p).status==='blocked')throw Error('충돌한 조건을 먼저 수정해 주세요.');return PAModelContract.makeRequest(registry,p,'선택한 재료를 실제로 함께 사용하는 고등학교 수학 문항 한 개를 제작하세요. 필요한 조건과 가교를 보완하되 선택한 생각을 장식으로 붙이지 마세요.\n계산 부담: '+calcChoices[calculation].join(' — ')+'\n추론 요구: '+reasonChoices[reasoning].join(' — ')+'\n'+$('brief').value,'REQ-'+crypto.randomUUID());}
 function generationStatus(text){$('generationStatus').textContent=text;}
 $('brief').oninput=remember;
 $('saveRequest').onclick=()=>{try{pending=request();save(pending,'제작요청_'+pending.request_id+'.json');generationStatus('요청 파일을 저장했습니다. 이 번호에 맞는 결과를 불러올 수 있습니다.');}catch(e){generationStatus(e.message);}};
 $('savePrompt').onclick=async()=>{try{pending=request();await navigator.clipboard.writeText(PAModelContract.handoff(pending));generationStatus('현재 Codex 대화에 붙여 넣을 제작 요청을 복사했습니다.');}catch(e){generationStatus(e.message);}};
 $('importRequest').onchange=async()=>{try{if(busy)throw Error('진행 중인 제작이 끝난 뒤 다른 요청을 열어 주세요.');const v=await fileValue($('importRequest'));if(!v)return;if(v.schema!=='problem-atom/model-request/1'||v.registry_revision!==registry.revision)throw Error('요청 형식 또는 자산 판본이 다릅니다.');pending=PAModelContract.makeRequest(registry,v.seed_plan,v.brief,v.request_id);acceptPlan(v.seed_plan);render();generationStatus('제작 요청을 열었습니다. 같은 번호의 결과를 검사할 수 있습니다.');}catch(e){generationStatus(e.message);}};
 function showResult(output,job=pending){if(!job)throw Error('해당 문항의 제작 요청 파일을 먼저 열어 주세요.');const data=output.result||output,v=PAModelContract.validateResult(data,job,registry,engine),host=$('modelResult');host.replaceChildren();$('reviewBadge').textContent='독립 검산 대기';const notice=el('p',v.accepted?'형식·연결 검사 통과 · 수학 검산과 사람 검토 대기':'수정할 내용이 있습니다 · 아직 출제할 수 없습니다.','result-notice'+(v.accepted?' passed':''));host.append(notice);if(v.errors.length){const ul=el('ul',null,'result-errors');v.errors.forEach(e=>ul.append(el('li',e)));host.append(ul);}if(PAModelContract.schemaErrors(data,PAModelContract.RESULT_SCHEMA).length)return;host.append(el('h3',data.title));data.question.forEach(t=>host.append(math(t)));
  const details=(name,lines)=>{const d=el('details');d.append(el('summary',name));lines.forEach(t=>d.append(math(t)));host.append(d);};details('정답과 풀이',[data.answer,...data.solution]);details('각 조건을 넣은 이유',data.condition_roles.map(c=>c.condition+' → '+c.used_in+' / 빼면: '+c.removal_effect));details('실제 풀이의 계산과 추론',[data.work_estimate.calculation,data.work_estimate.reasoning,data.work_estimate.bottleneck]);details('사용한 재료',data.plan.nodes.map(n=>(ops.get(n.id)?.name||n.id)+' · '+n.scope));details('모델 자체 점검 · 독립 검산 아님',data.self_checks.map(c=>c.check+': '+c.result));if(data.new_bridge_proposals.length)details('새 연결 제안 · 검토 전',data.new_bridge_proposals.map(p=>p.name+': '+p.mathematical_argument));host.append(btn('문항과 풀이 저장',()=>save({result:data,validation:v},'제작결과_'+job.request_id+'.json')));}
 $('importResult').onchange=async()=>{try{if(busy)throw Error('제작이 끝난 뒤 다른 결과를 열어 주세요.');const data=await fileValue($('importResult'));if(data)showResult(data);}catch(e){generationStatus(e.message);}};
 $('connectSession').onclick=async()=>{if(session.local){await checkSession();generationStatus(sessionReady?'Codex 로그인 연결을 확인했습니다. 재료를 골라 제작하세요.':'Codex 로그인 또는 연결 도우미 상태를 확인하세요.');}else $('sessionDialog').showModal();};$('closeSession').onclick=()=>$('sessionDialog').close();$('openCompanion').onclick=()=>{session.open(effective(),$('brief').value,calculation,reasoning);$('sessionDialog').close();};
 async function checkSession(){if(!session.local){$('sessionBadge').textContent='Codex 연결';$('sessionDescription').textContent='API 키 없이 Codex 로그인으로 제작합니다. 먼저 이 PC의 연결 도우미 화면을 열어 주세요.';return;}try{const s=await session.status();sessionReady=s.ready&&s.revision===registry.revision;$('sessionBadge').textContent=sessionReady?'Codex 연결됨 · Sol':'로그인 확인 필요';$('connectSession').classList.toggle('connected',sessionReady);$('sessionDescription').textContent=s.revision!==registry.revision?'화면과 연결 도우미의 자산이 다릅니다. 도우미를 다시 시작하세요.':s.reason+' · Codex 이용 한도를 사용합니다.';if(s.activeJob&&!activeJob){activeJob=s.activeJob;busy=true;poll();}}catch(e){sessionReady=false;$('sessionBadge').textContent='연결 끊김';$('sessionDescription').textContent=e.message;}}
 async function historyList(){if(!session.local)return;try{const response=await session.jobs(),host=$('jobHistory');host.replaceChildren();if(!response.jobs.length)host.append(el('p','아직 제작 기록이 없습니다.','muted'));for(const j of response.jobs){const row=el('div',null,'job-row');row.append(el('span',new Date(j.createdAt).toLocaleString('ko-KR')+' · '+({running:'제작 중',completed:'결과 도착',failed:'실패',cancelled:'취소',interrupted:'중단'}[j.status]||j.status)),btn('열기',async()=>{try{const full=await session.job(j.id);pending=full.request;if(full.output)showResult(full.output,full.request);else generationStatus(full.message);if(full.status==='running'){activeJob=full.id;busy=true;poll();}}catch(e){generationStatus(e.message);}}));host.append(row);}}catch(e){$('jobHistory').textContent=e.message;}}
 async function poll(){clearTimeout(pollTimer);if(!activeJob)return;try{const j=await session.job(activeJob);pending=j.request;const elapsed=Math.max(0,Math.floor((Date.now()-Date.parse(j.createdAt))/1000));generationStatus(j.message+(j.status==='running'?' · '+Math.floor(elapsed/60)+'분 '+elapsed%60+'초 경과':''));if(j.status==='running'){busy=true;$('cancelJob').hidden=false;$('generate').disabled=true;pollTimer=setTimeout(poll,2000);}else{busy=false;activeJob=null;$('cancelJob').hidden=true;if(j.output)showResult(j.output,j.request);render();historyList();}}catch(e){generationStatus(e.message+' 제작 기록에서 완료 여부를 확인하세요.');busy=false;$('cancelJob').hidden=true;render();}}
 $('generate').onclick=async()=>{if(busy)return;if(!session.local){$('sessionDialog').showModal();return;}try{if(!sessionReady)await checkSession();if(!sessionReady)throw Error('Codex에서 ChatGPT 로그인 상태를 확인하세요.');pending=request();busy=true;render();generationStatus('선택한 원자를 Codex Sol에 전달하고 있습니다.');const j=await session.submit(pending);activeJob=j.id;poll();}catch(e){busy=false;render();generationStatus(e.message);}};
 $('cancelJob').onclick=async()=>{try{if(activeJob){await session.cancel(activeJob);generationStatus('취소를 요청했습니다.');poll();}}catch(e){generationStatus(e.message);}};
 $('assetCount').textContent='연결 재료 '+registry.operations.length+'개 · 원본 '+registry.records.length+'개';renderFilters();renderChoices();render();await checkSession();await historyList();if(!$('loadStatus').textContent)$('loadStatus').textContent='선택한 재료와 목표는 이 브라우저에 자동 저장됩니다.';
}catch(e){$('loadStatus').textContent='제작실을 열지 못했습니다: '+e.message;}
})();
