(async()=>{'use strict';
 const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;};
 const btn=(text,fn,cls)=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;};
 function save(value,name){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=el('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 function math(text){const p=el('p');let at=0;for(const m of String(text).matchAll(/\$\$([\s\S]+?)\$\$|\$([^$\n]+?)\$/g)){p.append(document.createTextNode(text.slice(at,m.index)));const span=el('span');if(window.katex)katex.render(m[1]||m[2],span,{displayMode:!!m[1],throwOnError:false,trust:false,maxExpand:1000});else span.textContent=m[0];p.append(span);at=m.index+m[0].length;}p.append(document.createTextNode(text.slice(at)));return p;}
 try{
  if(window.PAAccount?.enabled)await PAAccount.ready;
  const res=await fetch('connection-registry.json',{cache:'no-store'});if(!res.ok)throw Error('분석 자산을 읽지 못했습니다. 새로고침해 주세요.');
  const registry=await res.json(),D=PAProblemDesign,T=PADesignControls,U=PACurriculum,C=PAModelContract,engine=PAConnections.create(registry),session=PASession.create(),reviewStore=PAReviewClient.create(session);
  const key=window.PAAccount?.storageKey('pa-problem-design-v1')||'pa-problem-design-v1';
  let state=D.defaults(),previous=null,tab='forms',pending=null,productionIO=null,busy=false,activeJob=null,pollTimer=null,sessionReady=false,companionControlsVersion=null,reviewError='',reviewTask=null;
  const calc=[['가볍게','긴 전개와 큰 수 계산을 줄입니다.'],['보통','핵심 식을 세운 뒤 필요한 만큼 계산합니다.'],['충분히','여러 단계의 식 정리와 계산을 허용합니다.']];
  const reasoning=[['기본','배운 방법을 찾아 바로 적용하는 문제'],['심화','여러 조건을 연결해 풀이 방향을 찾는 문제'],['고난도','숨은 관계·역추론·경우 분류가 필요한 문제']];
  function notice(t){$('loadStatus').textContent=t;}
  function generationStatus(t){$('generationStatus').textContent=t;}
  function snapshot(){return {schema:'problem-atom/design-draft/1',design:structuredClone(state),brief:$('brief').value};}
  function remember(){try{localStorage.setItem(key,JSON.stringify(snapshot()));}catch(_){notice('자동 저장이 어렵습니다. 아래 저장·불러오기에서 제작 조건을 파일로 저장하세요.');}}
  function accept(value){if(value?.schema!=='problem-atom/design-draft/1'||typeof value.brief!=='string'||value.brief.length>5000)throw Error('제작 조건 파일이 아닙니다. 이전 풀이 지도 파일은 원본을 보관해 주세요.');const next=D.normalize({...value.design,tuning:undefined},registry);if(value.design.tuning!==undefined)next.tuning=T.normalize(value.design.tuning);state=next;$('brief').value=value.brief;}
  try{const raw=localStorage.getItem(key);if(raw)accept(JSON.parse(raw));else{const legacyRaw=localStorage.getItem(window.PAAccount?.storageKey('pa-compose-boxes-v1')||'pa-compose-boxes-v1');if(legacyRaw){const legacy=JSON.parse(legacyRaw),ids=new Set((legacy.plan?.nodes||[]).map(n=>n.id));if(ids.size){const scope=legacy.unitScope||U.scope('m2-integrals');if(scope.unit&&U.count(registry,scope.unit))state.curriculum_scope=scope;state.elements=[...D.forms,...D.conditions].filter(e=>e.operations.some(id=>ids.has(id))&&D.available(e,state.curriculum_scope,registry)).slice(0,4).map(e=>e.id);$('brief').value=String(legacy.brief||'').slice(0,5000);notice('이전 풀이 지도는 보관하고, 관련된 핵심 조건을 불러왔습니다. 새 방식에 맞게 확인해 주세요.');const keep=btn('이전 풀이 지도 원본 저장',()=>save(legacy,'이전_풀이지도.json'));document.querySelector('#workspaceTools .file-tools').append(keep);}}}}catch(e){notice('저장된 조건을 자동으로 적용하지 못했습니다. 기존 저장본은 유지했습니다. '+e.message);}
  if(location.hash.startsWith('#design=')){try{previous=snapshot();accept(JSON.parse(decodeURIComponent(location.hash.slice(8))));history.replaceState(null,'',location.pathname+location.search);notice('공개 화면에서 고른 제작 조건을 가져왔습니다.');}catch(e){notice(e.message);}}
  const params=new URLSearchParams(location.search),requestedUnit=params.get('unit');
  if(requestedUnit){if(U.get(requestedUnit)&&U.count(registry,requestedUnit)){state.curriculum_scope=U.scope(requestedUnit);state.elements=state.elements.filter(id=>D.available(D.byId.get(id),state.curriculum_scope,registry));state.branches=state.branches.filter(id=>D.available(D.byId.get(id),state.curriculum_scope,registry));}else notice('요청한 대단원은 아직 분석 재료가 0개입니다. 현재 재료가 있는 대단원으로 시작합니다.');}
  if(params.get('mode')==='fusion')notice('과목 융합은 아직 다른 과목의 제작 재료가 없어 열리지 않았습니다. 현재 등록된 수학Ⅱ 범위에서 제작할 수 있습니다.');
  const reviewed=params.get('reviewed');if(reviewed){const match=D.all.find(e=>e.operations.includes(reviewed));if(match){const unit=U.classifications[reviewed]?.main[0]||'m2-integrals';state.curriculum_scope=U.scope(unit);state.elements=[];state.branches=[];state[D.forms.includes(match)||D.conditions.includes(match)?'elements':'branches']=[match.id];notice('검수한 재료와 연결되는 제작 조건을 골랐습니다: '+match.name);}else notice('이 재료는 풀이를 구성할 때 쓰는 보조 판단입니다. 분석 자산에 연결되어 있으며 AI가 필요할 때 사용합니다.');}
  function change(fn,{redraw=false}={}){previous=snapshot();fn();if(redraw)render();else renderSummary();remember();}
  function select(id,group,on){change(()=>{state[group]=on?[...new Set([...state[group],id])]:state[group].filter(x=>x!==id);});}
  function card(entry,group){const box=el('article',null,'feature-card'),label=el('label',null,'feature-choice'),input=el('input');input.type='checkbox';input.value=entry.id;input.checked=state[group].includes(entry.id);input.setAttribute('aria-label',entry.name);input.onchange=()=>select(entry.id,group,input.checked);label.append(input,el('span',entry.name));box.append(label,el('p',entry.why,'feature-description'));const details=el('details'),summary=el('summary','간단한 예시 보기'),example=el('div',null,'feature-example');example.append(math(entry.example));details.append(summary,example);box.append(details);return box;}
  function entries(list){return list.filter(e=>D.available(e,state.curriculum_scope,registry));}
  function renderCards(){const list=entries(tab==='forms'?D.forms:D.conditions);$('featureCards').replaceChildren(...list.map(e=>card(e,'elements')));$('featureCards').setAttribute('aria-labelledby',tab==='forms'?'formsTab':'conditionsTab');for(const t of ['forms','conditions']){$(t+'Tab').setAttribute('aria-selected',String(tab===t));$(t+'Tab').tabIndex=tab===t?0:-1;$(t+'Count').textContent=entries(t==='forms'?D.forms:D.conditions).length+'개';}if(!list.length)$('featureCards').append(el('p','이 범위에는 아직 해당 조건이 없습니다. 조건을 지정하지 않고 제작할 수 있습니다.'));}
  function renderBranches(){const open=new Set([...$('branchGroups').querySelectorAll('details[open][data-group]')].map(e=>e.dataset.group));$('branchGroups').replaceChildren();for(const group of D.branches){const list=entries(group.items);if(!list.length)continue;const details=el('details',null,'branch-group');details.dataset.group=group.id;details.open=open.has(group.id)||list.some(e=>state.branches.includes(e.id));const summary=el('summary',group.name),count=el('span');count.dataset.branchCount=group.id;summary.append(count);details.append(summary,el('p',group.description));const host=el('div',null,'branch-items');host.append(...list.map(e=>card(e,'branches')));details.append(host);$('branchGroups').append(details);}}
  function choices(id,field,list){const host=$(id);host.replaceChildren();list.forEach(([name],i)=>{const label=el('label'),input=el('input');input.type='radio';input.name=field;input.value=i;input.checked=state[field]===i;input.onchange=()=>change(()=>state[field]=i);label.append(input,el('span',name));host.append(label);});}
  const tuningGroups=[['단서',['disclosure','candidates']],['풀이',['branching','boundary','representation','coupling']],['질문·변형',['target','numbers','answer_form','variation']]];
  function renderTuning(){
   const host=$('tuningFields');if(host.childElementCount)return;
   for(const [name,ids] of tuningGroups){const group=el('fieldset',null,'tuning-group');group.append(el('legend',name));const grid=el('div',null,'tuning-grid');
    for(const id of ids){const control=T.controls.find(c=>c.id===id),field=el('div',null,'tuning-field'),label=el('label',control.label),input=el('select'),description=el('p',control.description,'tuning-description'),example=el('p',null,'tuning-example');
     input.id='tuning-'+id;label.htmlFor=input.id;description.id=input.id+'-description';example.id=input.id+'-example';input.setAttribute('aria-describedby',description.id+' '+example.id);example.setAttribute('aria-live','polite');
     for(const option of control.options){const item=el('option',option.label);item.value=option.value;input.append(item);}
     input.onchange=()=>change(()=>{state.tuning=state.tuning?T.normalize(state.tuning):T.defaults();state.tuning.values[id]=input.value;});field.append(label,description,input,example);grid.append(field);
    }group.append(grid);host.append(group);
   }
  }
  function syncTuning(){
   const values=state.tuning?T.normalize(state.tuning).values:T.defaults().values,selected=T.controls.filter(c=>values[c.id]!=='auto'),errors=state.tuning?T.conflicts(state.tuning):[];
   for(const control of T.controls){const input=$('tuning-'+control.id);if(!input)continue;input.value=values[control.id];$(input.id+'-example').textContent=control.options.find(o=>o.value===input.value).example;}
   $('tuningCount').textContent=errors.length?'설정 충돌 '+errors.length+'건':selected.length?selected.length+'개 지정':'모두 AI에게 맡김';$('resetTuning').disabled=!selected.length;
   const conflict=$('tuningConflicts');conflict.replaceChildren();conflict.hidden=!errors.length;if(errors.length){conflict.append(el('p','아래 설정을 함께 사용할 수 없습니다.'));const list=el('ul');errors.forEach(message=>list.append(el('li',message)));conflict.append(list);$('designTuning').open=true;}
   $('tuningSummary').textContent=selected.length?'세부 조절 '+selected.length+'개 지정'+(errors.length?' · 충돌을 먼저 해결해 주세요.':''):'';
   $('goToMake').disabled=errors.length>0;
   return errors;
  }
  function requireTuningCompatible(){const errors=syncTuning();if(errors.length){$('tuningConflicts').focus();throw Error(errors.join(' '));}}
  function renderSummary(){const host=$('selectedSummary');host.replaceChildren();for(const [key,label] of [['elements','핵심 조건'],['branches','추론 갈래']]){if(!state[key].length)continue;host.append(el('p',label,'summary-label'));for(const id of state[key]){const entry=D.byId.get(id),chip=el('span',null,'selected-chip'),remove=btn('×',()=>change(()=>{state[key]=state[key].filter(x=>x!==id);},{redraw:true}));remove.setAttribute('aria-label',entry.name+' 선택 해제');chip.append(el('span',entry.name),remove);host.append(chip);}}if(!state.elements.length&&!state.branches.length)host.append(el('p','핵심 조건은 AI에게 맡깁니다. 대단원과 아래 난도 목표만으로 시작할 수 있어요.','summary-empty'));
   $('mobileSelectionCount').textContent='선택 '+(state.elements.length+state.branches.length)+'개';
   $('calculationHint').textContent=calc[state.calculation][1];$('reasoningHint').textContent=reasoning[state.reasoning][1];$('undoSelection').disabled=!previous;$('clearAll').disabled=!state.elements.length&&!state.branches.length;
   $('designWarning').textContent=state.elements.length+state.branches.length>4?'선택이 많으면 조건끼리 충돌하거나 풀이가 복잡해질 수 있습니다. 꼭 필요한 조건 2~3개부터 권합니다.':'';
   for(const group of D.branches){const c=document.querySelector('[data-branch-count="'+group.id+'"]');if(c)c.textContent=group.items.filter(e=>state.branches.includes(e.id)).length+'개 선택';}syncTuning();
  }
  function render(){renderCards();renderBranches();renderTuning();choices('calculationOptions','calculation',calc);choices('reasoningOptions','reasoning',reasoning);$('unitSelect').value=state.curriculum_scope.unit;$('scopeStock').textContent='대단원 자산 '+U.count(registry,state.curriculum_scope.unit)+'개 · 보조 재료는 자동 연결';renderSummary();}
  for(const subject of U.subjects){const group=el('optgroup');group.label=subject.name;for(const unit of U.units.filter(u=>u.subject===subject.id)){const count=U.count(registry,unit.id),option=el('option',unit.name+' · 자산 '+count+'개');option.value=unit.id;option.disabled=!count;group.append(option);}$('unitSelect').append(group);}
  $('unitSelect').onchange=()=>change(()=>{state.curriculum_scope=U.scope($('unitSelect').value);const removed=[...state.elements,...state.branches].filter(id=>!D.available(D.byId.get(id),state.curriculum_scope,registry));state.elements=state.elements.filter(id=>!removed.includes(id));state.branches=state.branches.filter(id=>!removed.includes(id));notice(removed.length?'범위에 맞지 않는 선택을 해제했습니다: '+removed.map(id=>D.byId.get(id).name).join(', '):'대단원을 바꿨습니다.');},{redraw:true});
  for(const name of ['forms','conditions']){$(name+'Tab').onclick=()=>{tab=name;renderCards();};$(name+'Tab').onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();tab=e.key==='Home'?'forms':e.key==='End'?'conditions':tab==='forms'?'conditions':'forms';renderCards();$(tab+'Tab').focus();}};}
  $('clearAll').onclick=()=>change(()=>{state.elements=[];state.branches=[];},{redraw:true});$('undoSelection').onclick=()=>{if(!previous)return;const current=snapshot();accept(previous);previous=current;render();remember();};$('brief').oninput=remember;
  $('resetTuning').onclick=()=>change(()=>{state.tuning=T.defaults();});
  $('mobileSettings').onclick=()=>{document.querySelector('.design-summary').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('summaryTitle').tabIndex=-1;$('summaryTitle').focus({preventScroll:true});};
  $('goToMake').onclick=()=>{$('production').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('productionTitle').tabIndex=-1;$('productionTitle').focus({preventScroll:true});};
  async function refreshReviews(){if(reviewTask)return reviewTask;reviewTask=(async()=>{try{await reviewStore.load();reviewStore.attach(registry);reviewError='';$('reviewStatus').textContent='사람이 검수한 연결 자료 '+registry.reviewed_assets.length+'건을 함께 참고합니다.';return true;}catch(e){reviewError=e.message;$('reviewStatus').textContent='검수 기록 확인 실패: '+reviewError;return false;}finally{reviewTask=null;}})();return reviewTask;}
  await refreshReviews();
  function request(){requireTuningCompatible();if(reviewError)throw Error('검수 기록을 확인하지 못했습니다. 새로고침 후 다시 제작해 주세요. '+reviewError);return C.makeRequest(registry,{revision:registry.revision,facts:[],nodes:[]},'선택한 제작 조건을 모두 실제 문항에 반영하고, 풀이 경로와 완전한 해설을 함께 구성하세요.\n'+$('brief').value,'REQ-'+crypto.randomUUID(),{...state,tuning:state.tuning||T.defaults()});}
  async function fileValue(input){const file=input.files[0];if(!file)return null;if(file.size>2000000)throw Error('2MB 이하 JSON 파일만 열 수 있습니다.');return JSON.parse(await file.text());}
  $('savePlan').onclick=()=>save(snapshot(),'문항_제작조건.json');$('importPlan').onchange=async()=>{try{const value=await fileValue($('importPlan'));if(value){previous=snapshot();accept(value);render();remember();notice('제작 조건을 가져왔습니다.');}}catch(e){notice(e.message);}};
  $('saveRequest').onclick=()=>{try{pending=request();save(pending,'제작요청_'+pending.request_id+'.json');generationStatus('제작 요청을 저장했습니다.');}catch(e){generationStatus(e.message);}};
  $('importRequest').onchange=async()=>{try{if(busy)throw Error('제작이 끝난 뒤 가져오세요.');const value=await fileValue($('importRequest'));if(!value)return;pending=PAWebHandoff.canonicalRequest(value,registry);if(D.isDesign(pending.design_intent)){previous=snapshot();state=pending.design_intent;$('brief').value=pending.brief.slice(0,5000);render();remember();}generationStatus('제작 요청을 열었습니다. 해당 요청의 결과를 가져올 수 있습니다.');}catch(e){generationStatus(e.message);}};
  function showDesignEvidence(evidence,host){
   const panel=el('details',null,'design-evidence');panel.append(el('summary','설계 근거와 설정 점검'),el('p','모델 자체 기록 · 독립 검산 아님. 아래 기록만으로 수학적 타당성이나 실행 가능한 연결이 확인되지는 않습니다.','evidence-caution'));
   const detail=(title,lines)=>{const section=el('details');section.append(el('summary',title));(lines.length?lines:['기록이 없습니다.']).forEach(line=>section.append(math(line)));panel.append(section);};
   const choice=(id,value)=>T.controls.find(c=>c.id===id)?.options.find(o=>o.value===value)?.label||(value==='unmet'?'미충족':value);
   detail('설정 충족',evidence.control_checks.map(row=>(T.controls.find(c=>c.id===row.parameter)?.label||row.parameter)+' · 요청: '+choice(row.parameter,row.requested)+' / 달성 기록: '+choice(row.parameter,row.achieved)+'\n해설 근거: '+row.solution_evidence+'\n설명: '+row.explanation));
   detail('원자 유도',evidence.derivation.map(row=>row.step_id+' · '+(row.kind==='registered'?'등록 연산':'잠재 결과')+' · 출발: '+row.source_ids.join(', ')+'\n앞 단계: '+(row.depends_on.join(', ')||'없음')+'\n전제: '+row.premises.join(' / ')+'\n대상·범위: '+row.scope+'\n결과: '+row.statement+'\n유도: '+row.argument+'\n실행 계약 자체 보고: '+(row.runtime_supported?'지원된다고 기록함':'새 연결 검토 필요')));
   const status={changed_answer:'다른 답을 만드는 예',not_necessary:'필요성 미확인',unresolved:'미해결'};
   detail('조건 제거',evidence.condition_tests.map(row=>row.condition+' · '+status[row.status]+'\n제거 뒤의 예: '+row.construction+'\n질문의 다른 답: '+row.alternative_target));
   detail('우회 점검',['시도한 풀이: '+evidence.shortcut_audit.route,'핵심 추론 유지 기록: '+(evidence.shortcut_audit.preserves_core?'유지':'우회로 건너뜀'),'판단 근거: '+evidence.shortcut_audit.reason]);
   detail('제작 구조',['숨은 함수족: '+evidence.structure.hidden_family,'정보 흐름: '+evidence.structure.information_flow,'분기: '+(evidence.structure.branch_points.join(' / ')||'없음'),'질문의 역할: '+evidence.structure.target_role,'이전 문항에서 바꾼 점: '+evidence.structure.variation_from_previous]);host.append(panel);
  }
  function showResult(output,job=pending){if(!job)throw Error('제작 요청을 먼저 열어 주세요.');const data=output.result||output,v=C.validateResult(data,job,registry,engine),host=$('modelResult');host.replaceChildren();$('reviewBadge').textContent='독립 검산 대기';host.append(el('p',v.accepted?'조건 대응·연결 검사 통과 · 독립 수학 검산 대기':'수정할 내용이 있습니다. 아직 출제할 수 없습니다.','result-notice'));if(v.errors.length){const ul=el('ul');v.errors.forEach(t=>ul.append(el('li',t)));host.append(ul);}if(C.schemaErrors(data,D.isDesign(job.design_intent)?C.resultSchema(registry,true,!!job.design_intent.tuning):C.RESULT_SCHEMA).length)return;
   host.append(el('h3',data.title));data.question.forEach(t=>host.append(math(t)));const detail=(name,lines)=>{const d=el('details');d.append(el('summary',name));lines.forEach(t=>d.append(math(t)));host.append(d);};detail('정답과 해설',[data.answer,...data.solution]);if(data.design_coverage?.length)detail('선택한 조건이 쓰인 곳',data.design_coverage.map(r=>D.byId.get(r.element_id)?.name+' → '+r.question_evidence+' / '+r.solution_evidence));detail('조건을 넣은 이유',data.condition_roles.map(c=>c.condition+' → '+c.used_in+' / 빼면: '+c.removal_effect));detail('실제 풀이의 계산과 추론',Object.values(data.work_estimate));detail('모델 자체 점검 · 독립 검산 아님',data.self_checks.map(c=>c.check+': '+c.result));if(data.design_evidence)showDesignEvidence(data.design_evidence,host);host.append(btn('문항과 풀이 저장',()=>save({request:job,result:data,validation:v},'제작결과_'+job.request_id+'.json')));if(v.accepted)host.append(btn('한글 출력에 담기',()=>{try{productionIO.add({request:job,result:data});$('printWorkbench').parentElement.open=true;$('printWorkbench').scrollIntoView({block:'start'});}catch(e){generationStatus(e.message);}},'primary'));}
  $('importResult').onchange=async()=>{try{if(busy)throw Error('제작이 끝난 뒤 가져오세요.');const data=await fileValue($('importResult'));if(data)showResult(data,data.request?PAWebHandoff.canonicalRequest(data.request,registry):pending);}catch(e){generationStatus(e.message);}};
  $('connectSession').onclick=async()=>{if(session.local)await checkSession();else $('sessionDialog').showModal();};$('closeSession').onclick=()=>$('sessionDialog').close();$('openCompanion').onclick=()=>{try{requireTuningCompatible();$('sessionDialogStatus').textContent='';session.openDesign(D.normalize(state,registry),$('brief').value);}catch(e){$('sessionDialogStatus').textContent=e.message;}};
  async function checkSession(){if(!session.local){productionIO?.capabilities(null);$('sessionBadge').textContent='Codex 연결';$('sessionDescription').textContent='이 PC의 연결 도우미에서 Codex 로그인으로 제작합니다. AI 웹 모드는 아래에서 바로 사용할 수 있습니다.';return;}try{const s=await session.status();companionControlsVersion=s.design_controls_version;productionIO?.capabilities(s);sessionReady=s.ready&&s.revision===registry.revision&&s.problem_design_version===1;$('sessionBadge').textContent=sessionReady?'Codex 연결됨 · Sol':'연결 확인 필요';$('sessionDescription').textContent=s.problem_design_version!==1||s.revision!==registry.revision?'제작실이 업데이트되었습니다. 최신 프로젝트 폴더에서 연결 도우미를 다시 시작하세요.':s.reason;if(s.activeJob&&!activeJob){activeJob=s.activeJob;busy=true;poll();}}catch(e){sessionReady=false;$('sessionBadge').textContent='연결 끊김';$('sessionDescription').textContent=e.message;}}
  async function historyList(){if(!session.local){$('historyPanel').hidden=true;return;}try{const response=await session.jobs(),host=$('jobHistory');host.replaceChildren();for(const j of response.jobs){host.append(btn(new Date(j.createdAt).toLocaleString('ko-KR')+' · '+({completed:'결과 도착',running:'제작 중',failed:'실패',cancelled:'취소'}[j.status]||j.status),async()=>{try{const full=await session.job(j.id);pending=full.request;if(full.output)showResult(full.output,full.request);else generationStatus(full.message);if(full.status==='running'){activeJob=full.id;busy=true;poll();}}catch(e){generationStatus(e.message);}}));}if(!response.jobs.length)host.append(el('p','아직 제작 기록이 없습니다.'));}catch(e){$('jobHistory').textContent=e.message;}}
  async function poll(){clearTimeout(pollTimer);if(!activeJob)return;try{const j=await session.job(activeJob);pending=j.request;generationStatus(j.message);if(j.status==='running'){busy=true;$('cancelJob').hidden=false;$('generate').disabled=true;pollTimer=setTimeout(poll,2000);}else{busy=false;activeJob=null;$('generate').disabled=false;$('cancelJob').hidden=true;if(j.output)showResult(j.output,j.request);historyList();}}catch(e){generationStatus(e.message+' 제작 기록에서 상태를 확인하세요.');busy=false;$('generate').disabled=false;$('cancelJob').hidden=true;}}
  $('generate').onclick=async()=>{if(busy)return;try{requireTuningCompatible();}catch(e){generationStatus(e.message);return;}if(!session.local){$('sessionDialog').showModal();return;}try{await checkSession();if(!sessionReady)throw Error($('sessionDescription').textContent);if(companionControlsVersion!==1)throw Error('이 연결 도우미는 세부 조절을 지원하지 않습니다. 최신 프로젝트 폴더에서 도우미를 다시 시작하세요.');if(!await refreshReviews())throw Error(reviewError);pending=request();busy=true;$('generate').disabled=true;generationStatus('제작 조건을 Codex Sol에 전달하고 있습니다.');const job=await session.submit(pending);activeJob=job.id;poll();}catch(e){busy=false;$('generate').disabled=false;generationStatus(e.message);}};
  $('cancelJob').onclick=async()=>{try{if(activeJob){await session.cancel(activeJob);generationStatus('취소를 요청했습니다.');poll();}}catch(e){generationStatus(e.message);}};
  productionIO=PAProductionIO.mount({registry,session,request,showResult});
  $('assetCount').textContent=registry.records.length+'개';$('assetStatus').textContent='분석 기록 '+registry.records.length+'개 · 풀이 연결 재료 '+registry.operations.length+'개. 원본 분석과 연결 규칙은 제작 요청에 함께 전달합니다.';
  render();window.addEventListener('focus',refreshReviews);window.addEventListener('storage',e=>{if(e.key===reviewStore.key)refreshReviews();});await checkSession();await historyList();
 }catch(e){$('loadStatus').textContent='제작실을 열지 못했습니다: '+e.message;}
})();
