(function(){'use strict';
 const $=id=>document.getElementById(id),element=(tag,text)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;return e;};
 const click=(text,fn)=>{const b=element('button',text);b.type='button';b.onclick=fn;return b;};
 const download=(value,name,type='application/json')=>{const blob=value instanceof Blob?value:new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type});const url=URL.createObjectURL(blob),a=element('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 function mount({registry,session,request,showResult}){
  const W=PAWebHandoff,C=PAModelContract,engine=PAConnections.create(registry),key='pa-print-bundle-v1',pendingKey='pa-web-pending-v1';
  let source='gemini',pending=null,items=[],exporting=false;
  const message=t=>{$('webStatus').textContent=t;},outputMessage=t=>{$('printStatus').textContent=t;};
  function canonical(item){const r=W.canonicalRequest(item.request,registry),v=C.validateResult(item.result,r,registry,engine);if(!v.accepted)throw Error('출력 전에 수정이 필요합니다: '+v.errors[0]);return {request:r,result:item.result};}
  function store(){try{localStorage.setItem(key,JSON.stringify(W.bundle(items)));}catch(_){outputMessage('브라우저 저장 공간이 부족합니다. 출력 묶음을 파일로 저장하세요.');}}
  function render(){const host=$('printItems');host.replaceChildren();items.forEach((item,i)=>{const row=element('li'),name=element('span',(i+1)+'. '+item.result.title);row.append(name,click('검토',()=>showResult({result:item.result},item.request)),click('빼기',()=>{items.splice(i,1);store();render();}));host.append(row);});$('printCount').textContent=items.length+'문항';$('downloadHwpx').disabled=!items.length||exporting;$('savePrintBundle').disabled=!items.length;$('emptyPrint').hidden=items.length>0;}
  function add(item){const value=canonical(item),old=items.find(i=>i.request.request_id===value.request.request_id);if(old){if(JSON.stringify(old.result)!==JSON.stringify(value.result))throw Error('같은 요청의 다른 결과가 담겨 있습니다. 기존 문항을 빼고 다시 담으세요.');outputMessage('이미 출력 목록에 담긴 문항입니다.');return;}if(items.length>=20)throw Error('한 번에 20문항까지 담을 수 있습니다.');items.push(value);store();render();outputMessage('출력 목록에 담았습니다. 독립 검산·사람 검토 상태는 바뀌지 않습니다.');}
  function refreshPrompt(){const provider=W.providers[source];$('webOpen').textContent=provider.name+' 열기';$('webOpen').href=provider.url;$('webPrompt').value=pending?W.prompt(pending,source):'';$('webRequestInfo').textContent=pending?'준비된 요청: '+pending.request_id+' · 이 요청을 보낸 대화의 답변을 가져오세요.':'풀이 지도를 완성하고 요청을 준비하세요.';$('clearWebPrompt').hidden=!pending;$('copyWebPrompt').disabled=!pending;$('saveWebPrompt').disabled=!pending;$('acceptWebResult').disabled=!pending;document.querySelectorAll('[data-web-provider]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.webProvider===source)));}
  document.querySelectorAll('[data-production-mode]').forEach(input=>input.onchange=()=>{const web=input.value==='web';$('webMode').hidden=!web;$('codexMode').hidden=web;$('productionModeLabel').textContent=web?'사용 중인 AI 웹에서 직접 제작':'Codex 로그인 세션 · Sol';});
  document.querySelectorAll('[data-web-provider]').forEach(b=>b.onclick=()=>{source=b.dataset.webProvider;refreshPrompt();try{if(pending)localStorage.setItem(pendingKey,JSON.stringify({source,request:pending}));}catch(_){}});
  $('prepareWebPrompt').onclick=()=>{try{pending=request();localStorage.setItem(pendingKey,JSON.stringify({source,request:pending}));refreshPrompt();message('요청을 준비했습니다. 복사한 뒤 AI 웹 대화에 붙여 넣으세요.');}catch(e){message(e.message);}};
  $('clearWebPrompt').onclick=()=>{pending=null;$('webResponse').value='';try{localStorage.removeItem(pendingKey);}catch(_){}refreshPrompt();message('준비한 요청을 비웠습니다. 풀이 지도와 제작 결과는 유지됩니다.');};
  $('copyWebPrompt').onclick=async()=>{try{await navigator.clipboard.writeText(W.prompt(pending,source));message('제작 요청을 복사했습니다. '+W.providers[source].name+'에서 붙여 넣고 전송하세요.');}catch(_){$('webPromptDetails').open=true;$('webPrompt').focus();$('webPrompt').select();message('아래 요청 내용을 직접 복사하세요.');}};
  $('saveWebPrompt').onclick=()=>download(W.prompt(pending,source),'제작요청_'+pending.request_id+'.txt','text/plain');
  $('acceptWebResult').onclick=async()=>{try{if(!pending)throw Error('제작 요청을 먼저 준비하세요.');const raw=W.parse($('webResponse').value),result=raw.result||raw;showResult({result},pending);const v=C.validateResult(result,pending,registry,engine);if(!v.accepted){message('답변을 표시했습니다. 결과의 수정 항목을 확인하세요.');return;}message('형식·연결 검사 통과 · 독립 수학 검산은 별도입니다.');if(session.local){try{await session.importResult({provider:source,request:pending,result});message('형식·연결 검사 통과 · 이 PC의 제작 기록에 보관했습니다. 독립 검산은 별도입니다.');}catch(e){message('결과는 표시했습니다. 기록 보관: '+e.message);}}}catch(e){message(e.message);}};
  $('downloadHwpx').onclick=async()=>{if(exporting||!items.length)return;exporting=true;render();try{outputMessage('편집 가능한 수식과 해설 미주를 조판하고 있습니다.');const file=await session.exportHwpx(W.bundle(items));download(file,'문항_'+items.length+'문항_해설미주.hwpx');outputMessage('HWPX를 내려받았습니다. 한글에서 수식·줄바꿈과 내용을 최종 검토하세요.');}catch(e){outputMessage(e.message);}finally{exporting=false;render();}};
  $('savePrintBundle').onclick=()=>download(W.bundle(items),'한글출력_문항묶음.json');
  $('loadPrintBundle').onchange=async()=>{try{const file=$('loadPrintBundle').files[0];if(!file)return;if(file.size>8000000)throw Error('8MB 이하 묶음만 열 수 있습니다.');const b=JSON.parse(await file.text());if(b.schema!=='problem-atom/document-bundle/1'||!Array.isArray(b.items)||!b.items.length||b.items.length>20)throw Error('문항 출력 묶음이 아닙니다.');const incoming=b.items.map(canonical),merged=[...items];for(const value of incoming){const old=merged.find(x=>x.request.request_id===value.request.request_id);if(old&&JSON.stringify(old.result)!==JSON.stringify(value.result))throw Error('같은 요청의 다른 문항이 있습니다. 기존 항목을 확인하세요.');if(!old)merged.push(value);}if(merged.length>20)throw Error('출력 목록은 20문항 이내로 구성하세요.');items=merged;store();render();outputMessage('출력 묶음을 불러왔습니다. 순서대로 미주 번호를 붙입니다.');}catch(e){outputMessage(e.message);}finally{$('loadPrintBundle').value='';}};
  try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved?.schema==='problem-atom/document-bundle/1'&&saved.items?.length<=20)items=saved.items.map(canonical);}catch(_){outputMessage('저장된 출력 묶음은 현재 자산으로 다시 검토해야 합니다. 원본 저장 내용은 유지했습니다.');}
  try{const saved=JSON.parse(localStorage.getItem(pendingKey)||'null');if(saved){pending=W.canonicalRequest(saved.request,registry);if(W.providers[saved.source])source=saved.source;}}catch(_){message('이전 웹 요청은 자산 판본이 달라 사용할 수 없습니다. 현재 구성으로 새 요청을 준비하세요.');}
  refreshPrompt();render();
  return {add,capabilities:s=>{if(!session.local)$('printHint').textContent='공개 화면에서는 출력 묶음을 저장하세요. 이 PC의 연결 도우미 화면에서 묶음을 가져와 HWPX로 출력할 수 있습니다.';else if(s?.hwpx_export_version!==1)$('printHint').textContent='한글 출력을 사용하려면 연결 도우미를 다시 시작하세요.';else if(!s.hwpx?.ready)$('printHint').textContent=s.hwpx?.reason||'한글 작성기 설치를 확인하세요.';}};
 }
 window.PAProductionIO={mount};
})();
