'use strict';
(()=>{
 const $=id=>document.getElementById(id),el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
 const math=(text,tag='p')=>{const p=el(tag);String(text).split(/(\$[^$]+\$)/g).forEach(s=>{if(s.startsWith('$')&&s.endsWith('$')){const span=el('span');try{katex.render(s.slice(1,-1),span,{throwOnError:true})}catch(_){span.textContent=s;}p.append(span);}else p.append(document.createTextNode(s));});return p;};
 const KEY='pa-studio-saved-v2';let saved=[];try{const raw=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(raw))saved=raw.filter(x=>x?.version===PAStudio.VERSION&&x.options&&Array.isArray(x.question)&&Array.isArray(x.solution)&&(()=>{try{PAStudio.generate(x.options);return true}catch(_){return false}})());}catch(_){}
 let current,batch=[],catalog;const recent=new Set();
 const levelLabel={guided:'기본',standard:'표준',challenge:'심화'};
 const options=()=>({family:$('family').value,level:document.querySelector('[name=level]:checked').value,calculation:document.querySelector('[name=calculation]:checked').value,seed:$('seed').value.trim()===''?NaN:Number($('seed').value)});
 const signature=row=>row.question.join('\n');
 const status=t=>$('status').textContent=t;
 function download(data,name,type='application/json'){const a=el('a');const u=URL.createObjectURL(new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 function preview(){try{const o=options(),r=PAStudio.generate(o),f=PAStudio.families[o.family];$('familySummary').textContent=f.summary;$('extensionLabel').textContent=f.extension;$('previewSteps').textContent=`생각 연결 ${r.steps.length}단계`;$('previewRoute').textContent=r.steps.join(' → ');$('previewWork').replaceChildren(...r.work.filter(x=>x[1]).map(([name,n])=>el('span',`${name} ${n}회`)));$('previewChange').textContent=o.level==='guided'?'중간 결론을 알려주어 핵심 판단을 연습합니다.':o.level==='challenge'?f.extension:'결론을 직접 주지 않고 원문의 조건에서 찾아내게 합니다.';$('makeBatch').disabled=false;$('replay').disabled=false;batch=[];$('variantTabs').replaceChildren();show(r,'예상 문항');status('아래 예상 문항을 보고 설정을 바꿔 보세요.');}catch(e){current=null;$('makeBatch').disabled=true;$('replay').disabled=true;$('saveItem').disabled=true;$('download').disabled=true;$('problem').replaceChildren(el('p',e.message));$('solution').replaceChildren();status(e.message);}}
 function show(r,title){current=r;$('seed').value=r.options.seed;$('resultTitle').textContent=title;$('problem').replaceChildren(Object.assign(el('p',`${levelLabel[r.options.level]} · ${r.family} · 번호 ${r.options.seed}`),{className:'meta'}),...r.question.map(s=>math(s)));$('saveItem').disabled=false;$('download').disabled=false;
 const detail=el('details');detail.append(el('summary','정답과 풀이 펼치기'));detail.append(Object.assign(el('p',`정답 ${r.answer}`),{className:'answer'}));r.solution.forEach((s,i)=>detail.append(math(`${i+1}. ${s}`)));const evidence=el('details');evidence.className='evidence';evidence.append(el('summary','쓴 요소·조건 역할·검산 범위'));
 evidence.append(el('p','새 문항은 검산한 생성 규칙을 적용합니다. 회귀검사는 구조별·경계별 표본이며, 모든 학생 풀이와 실측 난도를 검증한 것은 아닙니다.'));
 const names=new Map((catalog?.atoms||[]).map(a=>[a.id,a.name]));evidence.append(el('p',r.assets.map(id=>names.get(id)||id).join(' → ')));r.impact.forEach(i=>evidence.append(el('p',`${i.element}: ${i.without} ${i.with}`)));evidence.append(el('p',r.level_note));$('solution').replaceChildren(detail,evidence);
 }
 $('family').replaceChildren(...Object.entries(PAStudio.families).map(([id,f])=>{const n=el('option',f.name);n.value=id;return n;}));
 const linked=new URLSearchParams(location.search);if(linked.has('family')){try{const o={family:linked.get('family'),level:linked.get('level')||'standard',calculation:linked.get('calculation')||'light',seed:Number(linked.get('seed')||20)};PAStudio.generate(o);$('family').value=o.family;document.querySelector(`[name=level][value=${o.level}]`).checked=true;document.querySelector(`[name=calculation][value=${o.calculation}]`).checked=true;$('seed').value=o.seed;}catch(_){status('링크 설정을 읽지 못해 기본 설정으로 시작합니다.');}}
 $('family').onchange=preview;document.querySelectorAll('[name=level],[name=calculation]').forEach(n=>n.onchange=preview);
 $('seed').oninput=()=>{try{PAStudio.generate(options());$('replay').disabled=false;}catch(e){$('replay').disabled=true;status(e.message);}};
 $('replay').onclick=()=>{preview();status('설정과 번호로 같은 문항을 불러왔습니다.');};
 $('makeBatch').onclick=()=>{try{const o=options(),seen=new Set([...saved.map(signature),...recent]);batch=[];let nonce=new Uint32Array(1);crypto.getRandomValues(nonce);let seed=nonce[0]%2147483648;for(let i=0;i<200&&batch.length<3;i++){const r=PAStudio.generate({...o,seed:(seed+i)%2147483648}),sig=signature(r);if(!seen.has(sig)){seen.add(sig);recent.add(sig);batch.push(r);}}
 if(!batch.length){status('이 설정에서 새 수치 조합을 찾지 못했습니다. 구조나 계산 크기를 바꿔 주세요.');return;}
 $('variantTabs').replaceChildren(...batch.map((r,i)=>{const b=el('button',`문항 ${i+1}`);b.type='button';b.setAttribute('aria-pressed',String(i===0));b.onclick=()=>{$('variantTabs').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');show(r,`만들어진 문항 ${i+1}`);};return b;}));show(batch[0],'만들어진 문항 1');status(`${batch.length}개를 만들었습니다. 보관함과 이번 작업에서 만든 동일 문장은 제외했습니다.`);
 }catch(e){status(e.message);}};
 function renderSaved(){$('savedCount').textContent=saved.length;$('exportSaved').disabled=!saved.length;$('savedItems').replaceChildren();if(!saved.length){$('savedItems').append(el('p','남겨 둘 문항의 ‘이 문항 보관’을 누르세요.'));return;}
 saved.forEach(r=>{const row=el('div');row.className='saved-row';const b=el('button','다시 보기');b.onclick=()=>{$('family').value=r.options.family;document.querySelector(`[name=level][value=${r.options.level}]`).checked=true;document.querySelector(`[name=calculation][value=${r.options.calculation}]`).checked=true;$('seed').value=r.options.seed;preview();show(PAStudio.generate(r.options),'보관한 문항');};const remove=el('button','보관 해제');remove.onclick=()=>{const next=saved.filter(x=>x.id!==r.id);try{localStorage.setItem(KEY,JSON.stringify(next));saved=next;renderSaved();status('보관을 해제했습니다. 재현 번호로 다시 만들 수 있습니다.');}catch(_){status('보관함 변경을 저장하지 못했습니다.');}};row.append(el('span',`${r.family} · ${levelLabel[r.options.level]} · ${r.options.seed}`),b,remove);$('savedItems').append(row);});}
 $('saveItem').onclick=()=>{if(!current)return;if(saved.some(r=>signature(r)===signature(current))){status('이미 보관한 문항입니다.');return;}if(saved.length>=200){status('브라우저 보관함은 200개까지입니다. 파일로 저장해 주세요.');return;}const next=[...saved,current];try{localStorage.setItem(KEY,JSON.stringify(next));saved=next;renderSaved();status('이 브라우저의 보관함에 저장했습니다.');}catch(_){status('브라우저 저장 공간이 부족합니다. 문항·풀이 파일 저장을 이용하세요.');}};
 $('printItem').onclick=()=>{if(current)window.print();};
 $('downloadText').onclick=()=>{if(current)download(['# 문항',...current.question,'','## 정답',String(current.answer),'','## 풀이',...current.solution.map((s,i)=>`${i+1}. ${s}`),'','## 재현 설정',JSON.stringify(current.options),current.version].join('\n\n'),current.id+'.md','text/markdown;charset=utf-8');};
 $('download').onclick=()=>{if(current)download(current,current.id+'.json');};$('exportSaved').onclick=()=>download({schema:'problem-atom/item-collection/2.0',version:PAStudio.VERSION,items:saved},'문항-보관함.json');
 function renderCatalog(){const host=$('assetCatalog');host.replaceChildren();catalog.recipes.forEach(r=>{const d=el('details');d.className='recipe-assets';const s=el('summary',r.title);s.append(el('small',`${r.source_question_id} · ${r.authors.join(' · ')} · 요소 ${r.atom_ids.length}개`));d.append(s);r.atom_ids.forEach(id=>{const a=catalog.atoms.find(x=>x.id===id),box=el('details');box.className='atom';box.append(el('summary',a.name),el('p',`${a.input} → ${a.output}`),el('p',`쓸 수 있는 때: ${a.guard}`),el('p',`주의할 경우: ${a.failure}`));d.append(box);});const note=el('div');note.className='correction';r.corrections.forEach(t=>note.append(el('p',t)));d.append(note);const b=el('button','이 요소로 문제 만들기');b.onclick=()=>{$('family').value=r.id;preview();$('family').focus();};d.append(b);host.append(d);});}
 renderSaved();preview();fetch('composition-catalog.json?v=20260920',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{catalog=d;renderCatalog();if(current)show(current,$('resultTitle').textContent);}).catch(()=>{$('assetCatalog').textContent='자산 설명을 불러오지 못했습니다. 생성 기능은 사용할 수 있습니다.';});
})();
