const atoms=[
 {id:"concept",code:"C-FUN-001",type:"개념",stage:1,name:"접점과 중근의 동치",description:"그래프가 접한다는 조건을 함수값과 도함수가 동시에 0인 조건으로 읽는다.",vector:[1,0,0,2]},
 {id:"pattern",code:"P-FUN-004",type:"유형",stage:1,name:"교점 개수-실근 구조",description:"두 그래프의 교점 개수 문제를 차함수의 실근 구조 문제로 바꾼다.",vector:[1,1,0,2]},
 {id:"decision",code:"D-FUN-012",type:"판단",stage:2,name:"경계에서 중근을 검사",description:"교점 수가 바뀌는 경계를 보고 중근 조건을 선택한다.",vector:[2,1,0,3]},
 {id:"skill",code:"S-ALG-009",type:"스킬",stage:3,name:"연립식으로 매개변수 소거",description:"함수값·도함수 조건을 연립해 불필요한 미지수를 제거한다.",vector:[0,0,2,1]},
 {id:"strategy",code:"T-FUN-006",type:"전략",stage:4,name:"후보 생성 후 원식 검산",description:"경계 후보를 모두 만든 뒤 원래 교점 조건에 대입해 거짓 후보를 제거한다.",vector:[1,1,1,2]},
 {id:"concept2",code:"C-CAL-007",type:"개념",stage:1,name:"극값과 도함수 부호",description:"도함수의 부호 변화와 원함수의 극대·극소 관계를 사용한다.",vector:[1,0,0,2]},
 {id:"decision2",code:"D-CAL-014",type:"판단",stage:2,name:"교점 수 변화에서 극값 비교",description:"매개변수에 따라 실근 수가 달라지는 신호를 보고 극값과 기준값 비교를 선택한다.",vector:[2,2,0,3]},
 {id:"skill2",code:"S-CAL-011",type:"스킬",stage:3,name:"도함수 부호표 구성",description:"임계점과 부호를 계산해 단조구간과 극값 구조를 표현한다.",vector:[0,1,2,2]},
];
const selected=new Set(["pattern","decision","skill"]);const $=s=>document.querySelector(s);const controls={hint:$("#hint"),branch:$("#branch"),calc:$("#calc")};const labels={hint:["직접 제시","부분 암시","암시 제거"],branch:["단일 경로","2~3개","다중 분기"],calc:["정리된 수치","보통","고위험 계산"]};
function chosen(){return atoms.filter(a=>selected.has(a.id)).sort((a,b)=>a.stage-b.stage)}
function renderList(){const node=$("#atomList");node.innerHTML="";atoms.forEach(a=>{const b=document.createElement("button");b.type="button";b.className=`atom-card${selected.has(a.id)?" selected":""}`;b.setAttribute("aria-pressed",String(selected.has(a.id)));b.innerHTML=`<header><span>${a.code}</span><b>${a.type} · ${a.name}</b></header><p>${a.description}</p>`;b.onclick=()=>{selected.has(a.id)?selected.delete(a.id):selected.add(a.id);render()};node.append(b)})}
function vectorFor(items){const v=[0,0,0,0];items.forEach(a=>a.vector.forEach((x,i)=>v[i]+=x));v[0]+=Number(controls.hint.value)-1;v[1]+=Number(controls.branch.value)-1;v[2]+=Number(controls.calc.value)-1;return v.map(x=>Math.max(0,Math.min(4,x)))}
function level(v){const raw=.4*v[0]+.25*v[1]+.25*v[2]+.1*(4-v[3]);const n=Math.max(1,Math.min(5,1+Math.round(raw)));return [`기초 확인 · ${n}/5`,`개념 적용 · ${n}/5`,`중간 탐색 · ${n}/5`,`고난도 탐색 · ${n}/5`,`최상위 탐색 · ${n}/5`][n-1]}
function check(items){const kinds=new Set(items.map(x=>x.type));if(!items.length)return{type:"warn",text:"카드를 선택하세요."};if(!kinds.has("판단"))return{type:"warn",text:"학생 병목을 측정할 핵심 판단 카드가 필요합니다."};if(!kinds.has("유형"))return{type:"warn",text:"문항의 풀이 골격이 될 유형 카드가 필요합니다."};if(!kinds.has("스킬"))return{type:"warn",text:"선택한 판단을 실행할 스킬 카드가 필요합니다."};return{type:"ok",text:"유형 → 판단 → 스킬의 기본 연결이 성립합니다. 개념·전략을 더하면 설명과 검산이 완성됩니다."}}
function draft(items){if(!items.length)return{title:"5축 카드를 선택하세요.",body:"판단 카드를 중심으로 유형과 스킬을 연결합니다."};const cue=labels.hint[+controls.hint.value],branches=labels.branch[+controls.branch.value],calc=labels.calc[+controls.calc.value];return{title:"교점 개수 변화의 경계를 판단하는 병목 문항군",body:`목표 병목: 교점 개수가 바뀌는 상황에서 중근 조건을 선택하지 못함\n\n선택 카드: ${items.map(x=>`${x.type} ${x.name}`).join(" → ")}\n\n진단형: 핵심 판단 외 계산을 낮추고 중근 조건 선택 여부만 확인한다.\n교정형: ${cue} 수준으로 경계 신호를 제공한다.\n전이형: 그래프 대신 방정식·매개변수 표현으로 바꾼다.\n통합형: ${branches}와 ${calc}을 적용하고 다른 판단을 연결한다.\n\nAI는 각 유형 3개 후보와 해설·예상 오답을 만든다. 강사는 정답 유일성, 목표 병목, 교육과정, 원문 유사도와 사람의 수정 내역을 확인한다.`}}
function renderMath(el,value){el.textContent=value;if(window.renderMathInElement)window.renderMathInElement(el,{delimiters:[{left:"$$",right:"$$",display:true},{left:"$",right:"$",display:false},{left:"\\(",right:"\\)",display:false}],throwOnError:false})}
function render(){renderList();const items=chosen(),c=check(items),cn=$("#compatibility");cn.className=`compatibility ${c.type}`;cn.textContent=c.text;const chain=$("#chain");chain.innerHTML="";items.forEach((a,i)=>{if(i)chain.insertAdjacentHTML("beforeend","<i>→</i>");const s=document.createElement("span");s.textContent=`${a.type} ${a.name}`;chain.append(s)});if(!items.length)chain.textContent="선택된 카드 없음";const v=vectorFor(items);$("#levelLabel").textContent=level(v);const vn=$("#vector");vn.innerHTML="";["새 판단","분기","실행","압축"].forEach((name,i)=>{const d=document.createElement("div");d.innerHTML=`<b style="--score:${v[i]}">${v[i]}</b><small>${name}</small>`;vn.append(d)});const d=draft(items);$("#draftTitle").textContent=d.title;renderMath($("#draftBody"),d.body);Object.keys(controls).forEach(n=>$(`#${n}Value`).textContent=labels[n][+controls[n].value])}
const presets={entry:{atoms:["concept","pattern","decision"],hint:0,branch:0,calc:0},reasoning:{atoms:["pattern","decision","skill"],hint:2,branch:1,calc:0},fusion:{atoms:["concept","pattern","decision","skill","strategy"],hint:2,branch:2,calc:1}};
document.querySelectorAll(".controls input").forEach(x=>x.addEventListener("input",render));document.querySelectorAll("[data-preset]").forEach(b=>b.onclick=()=>{const p=presets[b.dataset.preset];selected.clear();p.atoms.forEach(x=>selected.add(x));Object.keys(controls).forEach(n=>controls[n].value=p[n]);render()});render();
